// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-aiq-backend/internal/platform/ent/device"
	"go-aiq-backend/internal/platform/ent/devicereading"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DeviceReadingCreate is the builder for creating a DeviceReading entity.
type DeviceReadingCreate struct {
	config
	mutation *DeviceReadingMutation
	hooks    []Hook
}

// SetDeviceID sets the "device_id" field.
func (_c *DeviceReadingCreate) SetDeviceID(v uuid.UUID) *DeviceReadingCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetPm10 sets the "pm1_0" field.
func (_c *DeviceReadingCreate) SetPm10(v float64) *DeviceReadingCreate {
	_c.mutation.SetPm10(v)
	return _c
}

// SetPm25 sets the "pm2_5" field.
func (_c *DeviceReadingCreate) SetPm25(v float64) *DeviceReadingCreate {
	_c.mutation.SetPm25(v)
	return _c
}

// SetPm100 sets the "pm10_0" field.
func (_c *DeviceReadingCreate) SetPm100(v float64) *DeviceReadingCreate {
	_c.mutation.SetPm100(v)
	return _c
}

// SetPmsProvider sets the "pms_provider" field.
func (_c *DeviceReadingCreate) SetPmsProvider(v string) *DeviceReadingCreate {
	_c.mutation.SetPmsProvider(v)
	return _c
}

// SetAqi sets the "aqi" field.
func (_c *DeviceReadingCreate) SetAqi(v int) *DeviceReadingCreate {
	_c.mutation.SetAqi(v)
	return _c
}

// SetTemperature sets the "temperature" field.
func (_c *DeviceReadingCreate) SetTemperature(v float64) *DeviceReadingCreate {
	_c.mutation.SetTemperature(v)
	return _c
}

// SetHumidity sets the "humidity" field.
func (_c *DeviceReadingCreate) SetHumidity(v float64) *DeviceReadingCreate {
	_c.mutation.SetHumidity(v)
	return _c
}

// SetHeatIndex sets the "heat_index" field.
func (_c *DeviceReadingCreate) SetHeatIndex(v float64) *DeviceReadingCreate {
	_c.mutation.SetHeatIndex(v)
	return _c
}

// SetTemperatureProvider sets the "temperature_provider" field.
func (_c *DeviceReadingCreate) SetTemperatureProvider(v string) *DeviceReadingCreate {
	_c.mutation.SetTemperatureProvider(v)
	return _c
}

// SetLat sets the "lat" field.
func (_c *DeviceReadingCreate) SetLat(v float64) *DeviceReadingCreate {
	_c.mutation.SetLat(v)
	return _c
}

// SetNillableLat sets the "lat" field if the given value is not nil.
func (_c *DeviceReadingCreate) SetNillableLat(v *float64) *DeviceReadingCreate {
	if v != nil {
		_c.SetLat(*v)
	}
	return _c
}

// SetLon sets the "lon" field.
func (_c *DeviceReadingCreate) SetLon(v float64) *DeviceReadingCreate {
	_c.mutation.SetLon(v)
	return _c
}

// SetNillableLon sets the "lon" field if the given value is not nil.
func (_c *DeviceReadingCreate) SetNillableLon(v *float64) *DeviceReadingCreate {
	if v != nil {
		_c.SetLon(*v)
	}
	return _c
}

// SetLocationProvider sets the "location_provider" field.
func (_c *DeviceReadingCreate) SetLocationProvider(v string) *DeviceReadingCreate {
	_c.mutation.SetLocationProvider(v)
	return _c
}

// SetNillableLocationProvider sets the "location_provider" field if the given value is not nil.
func (_c *DeviceReadingCreate) SetNillableLocationProvider(v *string) *DeviceReadingCreate {
	if v != nil {
		_c.SetLocationProvider(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceReadingCreate) SetCreatedAt(v time.Time) *DeviceReadingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeviceReadingCreate) SetNillableCreatedAt(v *time.Time) *DeviceReadingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDevice sets the "device" edge to the Device entity.
func (_c *DeviceReadingCreate) SetDevice(v *Device) *DeviceReadingCreate {
	return _c.SetDeviceID(v.ID)
}

// Mutation returns the DeviceReadingMutation object of the builder.
func (_c *DeviceReadingCreate) Mutation() *DeviceReadingMutation {
	return _c.mutation
}

// Save creates the DeviceReading in the database.
func (_c *DeviceReadingCreate) Save(ctx context.Context) (*DeviceReading, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceReadingCreate) SaveX(ctx context.Context) *DeviceReading {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceReadingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceReadingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceReadingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := devicereading.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceReadingCreate) check() error {
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "DeviceReading.device_id"`)}
	}
	if _, ok := _c.mutation.Pm10(); !ok {
		return &ValidationError{Name: "pm1_0", err: errors.New(`ent: missing required field "DeviceReading.pm1_0"`)}
	}
	if v, ok := _c.mutation.Pm10(); ok {
		if err := devicereading.Pm10Validator(v); err != nil {
			return &ValidationError{Name: "pm1_0", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.pm1_0": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Pm25(); !ok {
		return &ValidationError{Name: "pm2_5", err: errors.New(`ent: missing required field "DeviceReading.pm2_5"`)}
	}
	if v, ok := _c.mutation.Pm25(); ok {
		if err := devicereading.Pm25Validator(v); err != nil {
			return &ValidationError{Name: "pm2_5", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.pm2_5": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Pm100(); !ok {
		return &ValidationError{Name: "pm10_0", err: errors.New(`ent: missing required field "DeviceReading.pm10_0"`)}
	}
	if v, ok := _c.mutation.Pm100(); ok {
		if err := devicereading.Pm100Validator(v); err != nil {
			return &ValidationError{Name: "pm10_0", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.pm10_0": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PmsProvider(); !ok {
		return &ValidationError{Name: "pms_provider", err: errors.New(`ent: missing required field "DeviceReading.pms_provider"`)}
	}
	if v, ok := _c.mutation.PmsProvider(); ok {
		if err := devicereading.PmsProviderValidator(v); err != nil {
			return &ValidationError{Name: "pms_provider", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.pms_provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Aqi(); !ok {
		return &ValidationError{Name: "aqi", err: errors.New(`ent: missing required field "DeviceReading.aqi"`)}
	}
	if v, ok := _c.mutation.Aqi(); ok {
		if err := devicereading.AqiValidator(v); err != nil {
			return &ValidationError{Name: "aqi", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.aqi": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Temperature(); !ok {
		return &ValidationError{Name: "temperature", err: errors.New(`ent: missing required field "DeviceReading.temperature"`)}
	}
	if _, ok := _c.mutation.Humidity(); !ok {
		return &ValidationError{Name: "humidity", err: errors.New(`ent: missing required field "DeviceReading.humidity"`)}
	}
	if v, ok := _c.mutation.Humidity(); ok {
		if err := devicereading.HumidityValidator(v); err != nil {
			return &ValidationError{Name: "humidity", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.humidity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HeatIndex(); !ok {
		return &ValidationError{Name: "heat_index", err: errors.New(`ent: missing required field "DeviceReading.heat_index"`)}
	}
	if _, ok := _c.mutation.TemperatureProvider(); !ok {
		return &ValidationError{Name: "temperature_provider", err: errors.New(`ent: missing required field "DeviceReading.temperature_provider"`)}
	}
	if v, ok := _c.mutation.TemperatureProvider(); ok {
		if err := devicereading.TemperatureProviderValidator(v); err != nil {
			return &ValidationError{Name: "temperature_provider", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.temperature_provider": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Lat(); ok {
		if err := devicereading.LatValidator(v); err != nil {
			return &ValidationError{Name: "lat", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.lat": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Lon(); ok {
		if err := devicereading.LonValidator(v); err != nil {
			return &ValidationError{Name: "lon", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.lon": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeviceReading.created_at"`)}
	}
	if len(_c.mutation.DeviceIDs()) == 0 {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required edge "DeviceReading.device"`)}
	}
	return nil
}

func (_c *DeviceReadingCreate) sqlSave(ctx context.Context) (*DeviceReading, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceReadingCreate) createSpec() (*DeviceReading, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceReading{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(devicereading.Table, sqlgraph.NewFieldSpec(devicereading.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Pm10(); ok {
		_spec.SetField(devicereading.FieldPm10, field.TypeFloat64, value)
		_node.Pm10 = value
	}
	if value, ok := _c.mutation.Pm25(); ok {
		_spec.SetField(devicereading.FieldPm25, field.TypeFloat64, value)
		_node.Pm25 = value
	}
	if value, ok := _c.mutation.Pm100(); ok {
		_spec.SetField(devicereading.FieldPm100, field.TypeFloat64, value)
		_node.Pm100 = value
	}
	if value, ok := _c.mutation.PmsProvider(); ok {
		_spec.SetField(devicereading.FieldPmsProvider, field.TypeString, value)
		_node.PmsProvider = value
	}
	if value, ok := _c.mutation.Aqi(); ok {
		_spec.SetField(devicereading.FieldAqi, field.TypeInt, value)
		_node.Aqi = value
	}
	if value, ok := _c.mutation.Temperature(); ok {
		_spec.SetField(devicereading.FieldTemperature, field.TypeFloat64, value)
		_node.Temperature = value
	}
	if value, ok := _c.mutation.Humidity(); ok {
		_spec.SetField(devicereading.FieldHumidity, field.TypeFloat64, value)
		_node.Humidity = value
	}
	if value, ok := _c.mutation.HeatIndex(); ok {
		_spec.SetField(devicereading.FieldHeatIndex, field.TypeFloat64, value)
		_node.HeatIndex = value
	}
	if value, ok := _c.mutation.TemperatureProvider(); ok {
		_spec.SetField(devicereading.FieldTemperatureProvider, field.TypeString, value)
		_node.TemperatureProvider = value
	}
	if value, ok := _c.mutation.Lat(); ok {
		_spec.SetField(devicereading.FieldLat, field.TypeFloat64, value)
		_node.Lat = &value
	}
	if value, ok := _c.mutation.Lon(); ok {
		_spec.SetField(devicereading.FieldLon, field.TypeFloat64, value)
		_node.Lon = &value
	}
	if value, ok := _c.mutation.LocationProvider(); ok {
		_spec.SetField(devicereading.FieldLocationProvider, field.TypeString, value)
		_node.LocationProvider = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(devicereading.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   devicereading.DeviceTable,
			Columns: []string{devicereading.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeviceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DeviceReadingCreateBulk is the builder for creating many DeviceReading entities in bulk.
type DeviceReadingCreateBulk struct {
	config
	err      error
	builders []*DeviceReadingCreate
}

// Save creates the DeviceReading entities in the database.
func (_c *DeviceReadingCreateBulk) Save(ctx context.Context) ([]*DeviceReading, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeviceReading, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceReadingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceReadingCreateBulk) SaveX(ctx context.Context) []*DeviceReading {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceReadingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceReadingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
