// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-aiq-backend/internal/platform/ent/device"
	"go-aiq-backend/internal/platform/ent/devicereading"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DeviceCreate is the builder for creating a Device entity.
type DeviceCreate struct {
	config
	mutation *DeviceMutation
	hooks    []Hook
}

// SetDeviceID sets the "device_id" field.
func (_c *DeviceCreate) SetDeviceID(v string) *DeviceCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DeviceCreate) SetName(v string) *DeviceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIsOutdoor sets the "is_outdoor" field.
func (_c *DeviceCreate) SetIsOutdoor(v bool) *DeviceCreate {
	_c.mutation.SetIsOutdoor(v)
	return _c
}

// SetNillableIsOutdoor sets the "is_outdoor" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableIsOutdoor(v *bool) *DeviceCreate {
	if v != nil {
		_c.SetIsOutdoor(*v)
	}
	return _c
}

// SetIsPublic sets the "is_public" field.
func (_c *DeviceCreate) SetIsPublic(v bool) *DeviceCreate {
	_c.mutation.SetIsPublic(v)
	return _c
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableIsPublic(v *bool) *DeviceCreate {
	if v != nil {
		_c.SetIsPublic(*v)
	}
	return _c
}

// SetDeviceKey sets the "device_key" field.
func (_c *DeviceCreate) SetDeviceKey(v string) *DeviceCreate {
	_c.mutation.SetDeviceKey(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceCreate) SetCreatedAt(v time.Time) *DeviceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableCreatedAt(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeviceCreate) SetUpdatedAt(v time.Time) *DeviceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableUpdatedAt(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeviceCreate) SetID(v uuid.UUID) *DeviceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableID(v *uuid.UUID) *DeviceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddReadingIDs adds the "readings" edge to the DeviceReading entity by IDs.
func (_c *DeviceCreate) AddReadingIDs(ids ...int) *DeviceCreate {
	_c.mutation.AddReadingIDs(ids...)
	return _c
}

// AddReadings adds the "readings" edges to the DeviceReading entity.
func (_c *DeviceCreate) AddReadings(v ...*DeviceReading) *DeviceCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReadingIDs(ids...)
}

// Mutation returns the DeviceMutation object of the builder.
func (_c *DeviceCreate) Mutation() *DeviceMutation {
	return _c.mutation
}

// Save creates the Device in the database.
func (_c *DeviceCreate) Save(ctx context.Context) (*Device, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceCreate) SaveX(ctx context.Context) *Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceCreate) defaults() {
	if _, ok := _c.mutation.IsOutdoor(); !ok {
		v := device.DefaultIsOutdoor
		_c.mutation.SetIsOutdoor(v)
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		v := device.DefaultIsPublic
		_c.mutation.SetIsPublic(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := device.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := device.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := device.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceCreate) check() error {
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "Device.device_id"`)}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := device.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "Device.device_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Device.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := device.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Device.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsOutdoor(); !ok {
		return &ValidationError{Name: "is_outdoor", err: errors.New(`ent: missing required field "Device.is_outdoor"`)}
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`ent: missing required field "Device.is_public"`)}
	}
	if _, ok := _c.mutation.DeviceKey(); !ok {
		return &ValidationError{Name: "device_key", err: errors.New(`ent: missing required field "Device.device_key"`)}
	}
	if v, ok := _c.mutation.DeviceKey(); ok {
		if err := device.DeviceKeyValidator(v); err != nil {
			return &ValidationError{Name: "device_key", err: fmt.Errorf(`ent: validator failed for field "Device.device_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Device.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Device.updated_at"`)}
	}
	return nil
}

func (_c *DeviceCreate) sqlSave(ctx context.Context) (*Device, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceCreate) createSpec() (*Device, *sqlgraph.CreateSpec) {
	var (
		_node = &Device{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(device.Table, sqlgraph.NewFieldSpec(device.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(device.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IsOutdoor(); ok {
		_spec.SetField(device.FieldIsOutdoor, field.TypeBool, value)
		_node.IsOutdoor = value
	}
	if value, ok := _c.mutation.IsPublic(); ok {
		_spec.SetField(device.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if value, ok := _c.mutation.DeviceKey(); ok {
		_spec.SetField(device.FieldDeviceKey, field.TypeString, value)
		_node.DeviceKey = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ReadingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ReadingsTable,
			Columns: []string{device.ReadingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicereading.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DeviceCreateBulk is the builder for creating many Device entities in bulk.
type DeviceCreateBulk struct {
	config
	err      error
	builders []*DeviceCreate
}

// Save creates the Device entities in the database.
func (_c *DeviceCreateBulk) Save(ctx context.Context) ([]*Device, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Device, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceCreateBulk) SaveX(ctx context.Context) []*Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
