// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-aiq-backend/internal/platform/ent/device"
	"go-aiq-backend/internal/platform/ent/devicereading"
	"go-aiq-backend/internal/platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks     []Hook
	mutation  *DeviceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceUpdate) SetName(v string) *DeviceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableName(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIsOutdoor sets the "is_outdoor" field.
func (_u *DeviceUpdate) SetIsOutdoor(v bool) *DeviceUpdate {
	_u.mutation.SetIsOutdoor(v)
	return _u
}

// SetNillableIsOutdoor sets the "is_outdoor" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableIsOutdoor(v *bool) *DeviceUpdate {
	if v != nil {
		_u.SetIsOutdoor(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *DeviceUpdate) SetIsPublic(v bool) *DeviceUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableIsPublic(v *bool) *DeviceUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetDeviceKey sets the "device_key" field.
func (_u *DeviceUpdate) SetDeviceKey(v string) *DeviceUpdate {
	_u.mutation.SetDeviceKey(v)
	return _u
}

// SetNillableDeviceKey sets the "device_key" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDeviceKey(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDeviceKey(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdate) SetUpdatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddReadingIDs adds the "readings" edge to the DeviceReading entity by IDs.
func (_u *DeviceUpdate) AddReadingIDs(ids ...int) *DeviceUpdate {
	_u.mutation.AddReadingIDs(ids...)
	return _u
}

// AddReadings adds the "readings" edges to the DeviceReading entity.
func (_u *DeviceUpdate) AddReadings(v ...*DeviceReading) *DeviceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReadingIDs(ids...)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearReadings clears all "readings" edges to the DeviceReading entity.
func (_u *DeviceUpdate) ClearReadings() *DeviceUpdate {
	_u.mutation.ClearReadings()
	return _u
}

// RemoveReadingIDs removes the "readings" edge to DeviceReading entities by IDs.
func (_u *DeviceUpdate) RemoveReadingIDs(ids ...int) *DeviceUpdate {
	_u.mutation.RemoveReadingIDs(ids...)
	return _u
}

// RemoveReadings removes "readings" edges to DeviceReading entities.
func (_u *DeviceUpdate) RemoveReadings(v ...*DeviceReading) *DeviceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReadingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := device.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Device.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceKey(); ok {
		if err := device.DeviceKeyValidator(v); err != nil {
			return &ValidationError{Name: "device_key", err: fmt.Errorf(`ent: validator failed for field "Device.device_key": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeviceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeviceUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsOutdoor(); ok {
		_spec.SetField(device.FieldIsOutdoor, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(device.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeviceKey(); ok {
		_spec.SetField(device.FieldDeviceKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReadingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ReadingsTable,
			Columns: []string{device.ReadingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicereading.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReadingsIDs(); len(nodes) > 0 && !_u.mutation.ReadingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ReadingsTable,
			Columns: []string{device.ReadingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicereading.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReadingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ReadingsTable,
			Columns: []string{device.ReadingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicereading.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DeviceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (_u *DeviceUpdateOne) SetName(v string) *DeviceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableName(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIsOutdoor sets the "is_outdoor" field.
func (_u *DeviceUpdateOne) SetIsOutdoor(v bool) *DeviceUpdateOne {
	_u.mutation.SetIsOutdoor(v)
	return _u
}

// SetNillableIsOutdoor sets the "is_outdoor" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableIsOutdoor(v *bool) *DeviceUpdateOne {
	if v != nil {
		_u.SetIsOutdoor(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *DeviceUpdateOne) SetIsPublic(v bool) *DeviceUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableIsPublic(v *bool) *DeviceUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetDeviceKey sets the "device_key" field.
func (_u *DeviceUpdateOne) SetDeviceKey(v string) *DeviceUpdateOne {
	_u.mutation.SetDeviceKey(v)
	return _u
}

// SetNillableDeviceKey sets the "device_key" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDeviceKey(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDeviceKey(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdateOne) SetUpdatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddReadingIDs adds the "readings" edge to the DeviceReading entity by IDs.
func (_u *DeviceUpdateOne) AddReadingIDs(ids ...int) *DeviceUpdateOne {
	_u.mutation.AddReadingIDs(ids...)
	return _u
}

// AddReadings adds the "readings" edges to the DeviceReading entity.
func (_u *DeviceUpdateOne) AddReadings(v ...*DeviceReading) *DeviceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReadingIDs(ids...)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearReadings clears all "readings" edges to the DeviceReading entity.
func (_u *DeviceUpdateOne) ClearReadings() *DeviceUpdateOne {
	_u.mutation.ClearReadings()
	return _u
}

// RemoveReadingIDs removes the "readings" edge to DeviceReading entities by IDs.
func (_u *DeviceUpdateOne) RemoveReadingIDs(ids ...int) *DeviceUpdateOne {
	_u.mutation.RemoveReadingIDs(ids...)
	return _u
}

// RemoveReadings removes "readings" edges to DeviceReading entities.
func (_u *DeviceUpdateOne) RemoveReadings(v ...*DeviceReading) *DeviceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReadingIDs(ids...)
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := device.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Device.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceKey(); ok {
		if err := device.DeviceKeyValidator(v); err != nil {
			return &ValidationError{Name: "device_key", err: fmt.Errorf(`ent: validator failed for field "Device.device_key": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeviceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeviceUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsOutdoor(); ok {
		_spec.SetField(device.FieldIsOutdoor, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(device.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeviceKey(); ok {
		_spec.SetField(device.FieldDeviceKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReadingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ReadingsTable,
			Columns: []string{device.ReadingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicereading.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReadingsIDs(); len(nodes) > 0 && !_u.mutation.ReadingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ReadingsTable,
			Columns: []string{device.ReadingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicereading.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReadingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ReadingsTable,
			Columns: []string{device.ReadingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicereading.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
