// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-aiq-backend/internal/platform/ent/devicereading"
	"go-aiq-backend/internal/platform/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeviceReadingUpdate is the builder for updating DeviceReading entities.
type DeviceReadingUpdate struct {
	config
	hooks     []Hook
	mutation  *DeviceReadingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DeviceReadingUpdate builder.
func (_u *DeviceReadingUpdate) Where(ps ...predicate.DeviceReading) *DeviceReadingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPm10 sets the "pm1_0" field.
func (_u *DeviceReadingUpdate) SetPm10(v float64) *DeviceReadingUpdate {
	_u.mutation.ResetPm10()
	_u.mutation.SetPm10(v)
	return _u
}

// SetNillablePm10 sets the "pm1_0" field if the given value is not nil.
func (_u *DeviceReadingUpdate) SetNillablePm10(v *float64) *DeviceReadingUpdate {
	if v != nil {
		_u.SetPm10(*v)
	}
	return _u
}

// AddPm10 adds value to the "pm1_0" field.
func (_u *DeviceReadingUpdate) AddPm10(v float64) *DeviceReadingUpdate {
	_u.mutation.AddPm10(v)
	return _u
}

// SetPm25 sets the "pm2_5" field.
func (_u *DeviceReadingUpdate) SetPm25(v float64) *DeviceReadingUpdate {
	_u.mutation.ResetPm25()
	_u.mutation.SetPm25(v)
	return _u
}

// SetNillablePm25 sets the "pm2_5" field if the given value is not nil.
func (_u *DeviceReadingUpdate) SetNillablePm25(v *float64) *DeviceReadingUpdate {
	if v != nil {
		_u.SetPm25(*v)
	}
	return _u
}

// AddPm25 adds value to the "pm2_5" field.
func (_u *DeviceReadingUpdate) AddPm25(v float64) *DeviceReadingUpdate {
	_u.mutation.AddPm25(v)
	return _u
}

// SetPm100 sets the "pm10_0" field.
func (_u *DeviceReadingUpdate) SetPm100(v float64) *DeviceReadingUpdate {
	_u.mutation.ResetPm100()
	_u.mutation.SetPm100(v)
	return _u
}

// SetNillablePm100 sets the "pm10_0" field if the given value is not nil.
func (_u *DeviceReadingUpdate) SetNillablePm100(v *float64) *DeviceReadingUpdate {
	if v != nil {
		_u.SetPm100(*v)
	}
	return _u
}

// AddPm100 adds value to the "pm10_0" field.
func (_u *DeviceReadingUpdate) AddPm100(v float64) *DeviceReadingUpdate {
	_u.mutation.AddPm100(v)
	return _u
}

// SetPmsProvider sets the "pms_provider" field.
func (_u *DeviceReadingUpdate) SetPmsProvider(v string) *DeviceReadingUpdate {
	_u.mutation.SetPmsProvider(v)
	return _u
}

// SetNillablePmsProvider sets the "pms_provider" field if the given value is not nil.
func (_u *DeviceReadingUpdate) SetNillablePmsProvider(v *string) *DeviceReadingUpdate {
	if v != nil {
		_u.SetPmsProvider(*v)
	}
	return _u
}

// SetAqi sets the "aqi" field.
func (_u *DeviceReadingUpdate) SetAqi(v int) *DeviceReadingUpdate {
	_u.mutation.ResetAqi()
	_u.mutation.SetAqi(v)
	return _u
}

// SetNillableAqi sets the "aqi" field if the given value is not nil.
func (_u *DeviceReadingUpdate) SetNillableAqi(v *int) *DeviceReadingUpdate {
	if v != nil {
		_u.SetAqi(*v)
	}
	return _u
}

// AddAqi adds value to the "aqi" field.
func (_u *DeviceReadingUpdate) AddAqi(v int) *DeviceReadingUpdate {
	_u.mutation.AddAqi(v)
	return _u
}

// SetTemperature sets the "temperature" field.
func (_u *DeviceReadingUpdate) SetTemperature(v float64) *DeviceReadingUpdate {
	_u.mutation.ResetTemperature()
	_u.mutation.SetTemperature(v)
	return _u
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_u *DeviceReadingUpdate) SetNillableTemperature(v *float64) *DeviceReadingUpdate {
	if v != nil {
		_u.SetTemperature(*v)
	}
	return _u
}

// AddTemperature adds value to the "temperature" field.
func (_u *DeviceReadingUpdate) AddTemperature(v float64) *DeviceReadingUpdate {
	_u.mutation.AddTemperature(v)
	return _u
}

// SetHumidity sets the "humidity" field.
func (_u *DeviceReadingUpdate) SetHumidity(v float64) *DeviceReadingUpdate {
	_u.mutation.ResetHumidity()
	_u.mutation.SetHumidity(v)
	return _u
}

// SetNillableHumidity sets the "humidity" field if the given value is not nil.
func (_u *DeviceReadingUpdate) SetNillableHumidity(v *float64) *DeviceReadingUpdate {
	if v != nil {
		_u.SetHumidity(*v)
	}
	return _u
}

// AddHumidity adds value to the "humidity" field.
func (_u *DeviceReadingUpdate) AddHumidity(v float64) *DeviceReadingUpdate {
	_u.mutation.AddHumidity(v)
	return _u
}

// SetHeatIndex sets the "heat_index" field.
func (_u *DeviceReadingUpdate) SetHeatIndex(v float64) *DeviceReadingUpdate {
	_u.mutation.ResetHeatIndex()
	_u.mutation.SetHeatIndex(v)
	return _u
}

// SetNillableHeatIndex sets the "heat_index" field if the given value is not nil.
func (_u *DeviceReadingUpdate) SetNillableHeatIndex(v *float64) *DeviceReadingUpdate {
	if v != nil {
		_u.SetHeatIndex(*v)
	}
	return _u
}

// AddHeatIndex adds value to the "heat_index" field.
func (_u *DeviceReadingUpdate) AddHeatIndex(v float64) *DeviceReadingUpdate {
	_u.mutation.AddHeatIndex(v)
	return _u
}

// SetTemperatureProvider sets the "temperature_provider" field.
func (_u *DeviceReadingUpdate) SetTemperatureProvider(v string) *DeviceReadingUpdate {
	_u.mutation.SetTemperatureProvider(v)
	return _u
}

// SetNillableTemperatureProvider sets the "temperature_provider" field if the given value is not nil.
func (_u *DeviceReadingUpdate) SetNillableTemperatureProvider(v *string) *DeviceReadingUpdate {
	if v != nil {
		_u.SetTemperatureProvider(*v)
	}
	return _u
}

// SetLat sets the "lat" field.
func (_u *DeviceReadingUpdate) SetLat(v float64) *DeviceReadingUpdate {
	_u.mutation.ResetLat()
	_u.mutation.SetLat(v)
	return _u
}

// SetNillableLat sets the "lat" field if the given value is not nil.
func (_u *DeviceReadingUpdate) SetNillableLat(v *float64) *DeviceReadingUpdate {
	if v != nil {
		_u.SetLat(*v)
	}
	return _u
}

// AddLat adds value to the "lat" field.
func (_u *DeviceReadingUpdate) AddLat(v float64) *DeviceReadingUpdate {
	_u.mutation.AddLat(v)
	return _u
}

// ClearLat clears the value of the "lat" field.
func (_u *DeviceReadingUpdate) ClearLat() *DeviceReadingUpdate {
	_u.mutation.ClearLat()
	return _u
}

// SetLon sets the "lon" field.
func (_u *DeviceReadingUpdate) SetLon(v float64) *DeviceReadingUpdate {
	_u.mutation.ResetLon()
	_u.mutation.SetLon(v)
	return _u
}

// SetNillableLon sets the "lon" field if the given value is not nil.
func (_u *DeviceReadingUpdate) SetNillableLon(v *float64) *DeviceReadingUpdate {
	if v != nil {
		_u.SetLon(*v)
	}
	return _u
}

// AddLon adds value to the "lon" field.
func (_u *DeviceReadingUpdate) AddLon(v float64) *DeviceReadingUpdate {
	_u.mutation.AddLon(v)
	return _u
}

// ClearLon clears the value of the "lon" field.
func (_u *DeviceReadingUpdate) ClearLon() *DeviceReadingUpdate {
	_u.mutation.ClearLon()
	return _u
}

// SetLocationProvider sets the "location_provider" field.
func (_u *DeviceReadingUpdate) SetLocationProvider(v string) *DeviceReadingUpdate {
	_u.mutation.SetLocationProvider(v)
	return _u
}

// SetNillableLocationProvider sets the "location_provider" field if the given value is not nil.
func (_u *DeviceReadingUpdate) SetNillableLocationProvider(v *string) *DeviceReadingUpdate {
	if v != nil {
		_u.SetLocationProvider(*v)
	}
	return _u
}

// ClearLocationProvider clears the value of the "location_provider" field.
func (_u *DeviceReadingUpdate) ClearLocationProvider() *DeviceReadingUpdate {
	_u.mutation.ClearLocationProvider()
	return _u
}

// Mutation returns the DeviceReadingMutation object of the builder.
func (_u *DeviceReadingUpdate) Mutation() *DeviceReadingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceReadingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceReadingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceReadingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceReadingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceReadingUpdate) check() error {
	if v, ok := _u.mutation.Pm10(); ok {
		if err := devicereading.Pm10Validator(v); err != nil {
			return &ValidationError{Name: "pm1_0", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.pm1_0": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pm25(); ok {
		if err := devicereading.Pm25Validator(v); err != nil {
			return &ValidationError{Name: "pm2_5", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.pm2_5": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pm100(); ok {
		if err := devicereading.Pm100Validator(v); err != nil {
			return &ValidationError{Name: "pm10_0", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.pm10_0": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PmsProvider(); ok {
		if err := devicereading.PmsProviderValidator(v); err != nil {
			return &ValidationError{Name: "pms_provider", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.pms_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Aqi(); ok {
		if err := devicereading.AqiValidator(v); err != nil {
			return &ValidationError{Name: "aqi", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.aqi": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Humidity(); ok {
		if err := devicereading.HumidityValidator(v); err != nil {
			return &ValidationError{Name: "humidity", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.humidity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TemperatureProvider(); ok {
		if err := devicereading.TemperatureProviderValidator(v); err != nil {
			return &ValidationError{Name: "temperature_provider", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.temperature_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Lat(); ok {
		if err := devicereading.LatValidator(v); err != nil {
			return &ValidationError{Name: "lat", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.lat": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Lon(); ok {
		if err := devicereading.LonValidator(v); err != nil {
			return &ValidationError{Name: "lon", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.lon": %w`, err)}
		}
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DeviceReading.device"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeviceReadingUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeviceReadingUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeviceReadingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(devicereading.Table, devicereading.Columns, sqlgraph.NewFieldSpec(devicereading.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Pm10(); ok {
		_spec.SetField(devicereading.FieldPm10, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPm10(); ok {
		_spec.AddField(devicereading.FieldPm10, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Pm25(); ok {
		_spec.SetField(devicereading.FieldPm25, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPm25(); ok {
		_spec.AddField(devicereading.FieldPm25, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Pm100(); ok {
		_spec.SetField(devicereading.FieldPm100, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPm100(); ok {
		_spec.AddField(devicereading.FieldPm100, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PmsProvider(); ok {
		_spec.SetField(devicereading.FieldPmsProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Aqi(); ok {
		_spec.SetField(devicereading.FieldAqi, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAqi(); ok {
		_spec.AddField(devicereading.FieldAqi, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Temperature(); ok {
		_spec.SetField(devicereading.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemperature(); ok {
		_spec.AddField(devicereading.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Humidity(); ok {
		_spec.SetField(devicereading.FieldHumidity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHumidity(); ok {
		_spec.AddField(devicereading.FieldHumidity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.HeatIndex(); ok {
		_spec.SetField(devicereading.FieldHeatIndex, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHeatIndex(); ok {
		_spec.AddField(devicereading.FieldHeatIndex, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TemperatureProvider(); ok {
		_spec.SetField(devicereading.FieldTemperatureProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Lat(); ok {
		_spec.SetField(devicereading.FieldLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLat(); ok {
		_spec.AddField(devicereading.FieldLat, field.TypeFloat64, value)
	}
	if _u.mutation.LatCleared() {
		_spec.ClearField(devicereading.FieldLat, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Lon(); ok {
		_spec.SetField(devicereading.FieldLon, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLon(); ok {
		_spec.AddField(devicereading.FieldLon, field.TypeFloat64, value)
	}
	if _u.mutation.LonCleared() {
		_spec.ClearField(devicereading.FieldLon, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LocationProvider(); ok {
		_spec.SetField(devicereading.FieldLocationProvider, field.TypeString, value)
	}
	if _u.mutation.LocationProviderCleared() {
		_spec.ClearField(devicereading.FieldLocationProvider, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{devicereading.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceReadingUpdateOne is the builder for updating a single DeviceReading entity.
type DeviceReadingUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DeviceReadingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetPm10 sets the "pm1_0" field.
func (_u *DeviceReadingUpdateOne) SetPm10(v float64) *DeviceReadingUpdateOne {
	_u.mutation.ResetPm10()
	_u.mutation.SetPm10(v)
	return _u
}

// SetNillablePm10 sets the "pm1_0" field if the given value is not nil.
func (_u *DeviceReadingUpdateOne) SetNillablePm10(v *float64) *DeviceReadingUpdateOne {
	if v != nil {
		_u.SetPm10(*v)
	}
	return _u
}

// AddPm10 adds value to the "pm1_0" field.
func (_u *DeviceReadingUpdateOne) AddPm10(v float64) *DeviceReadingUpdateOne {
	_u.mutation.AddPm10(v)
	return _u
}

// SetPm25 sets the "pm2_5" field.
func (_u *DeviceReadingUpdateOne) SetPm25(v float64) *DeviceReadingUpdateOne {
	_u.mutation.ResetPm25()
	_u.mutation.SetPm25(v)
	return _u
}

// SetNillablePm25 sets the "pm2_5" field if the given value is not nil.
func (_u *DeviceReadingUpdateOne) SetNillablePm25(v *float64) *DeviceReadingUpdateOne {
	if v != nil {
		_u.SetPm25(*v)
	}
	return _u
}

// AddPm25 adds value to the "pm2_5" field.
func (_u *DeviceReadingUpdateOne) AddPm25(v float64) *DeviceReadingUpdateOne {
	_u.mutation.AddPm25(v)
	return _u
}

// SetPm100 sets the "pm10_0" field.
func (_u *DeviceReadingUpdateOne) SetPm100(v float64) *DeviceReadingUpdateOne {
	_u.mutation.ResetPm100()
	_u.mutation.SetPm100(v)
	return _u
}

// SetNillablePm100 sets the "pm10_0" field if the given value is not nil.
func (_u *DeviceReadingUpdateOne) SetNillablePm100(v *float64) *DeviceReadingUpdateOne {
	if v != nil {
		_u.SetPm100(*v)
	}
	return _u
}

// AddPm100 adds value to the "pm10_0" field.
func (_u *DeviceReadingUpdateOne) AddPm100(v float64) *DeviceReadingUpdateOne {
	_u.mutation.AddPm100(v)
	return _u
}

// SetPmsProvider sets the "pms_provider" field.
func (_u *DeviceReadingUpdateOne) SetPmsProvider(v string) *DeviceReadingUpdateOne {
	_u.mutation.SetPmsProvider(v)
	return _u
}

// SetNillablePmsProvider sets the "pms_provider" field if the given value is not nil.
func (_u *DeviceReadingUpdateOne) SetNillablePmsProvider(v *string) *DeviceReadingUpdateOne {
	if v != nil {
		_u.SetPmsProvider(*v)
	}
	return _u
}

// SetAqi sets the "aqi" field.
func (_u *DeviceReadingUpdateOne) SetAqi(v int) *DeviceReadingUpdateOne {
	_u.mutation.ResetAqi()
	_u.mutation.SetAqi(v)
	return _u
}

// SetNillableAqi sets the "aqi" field if the given value is not nil.
func (_u *DeviceReadingUpdateOne) SetNillableAqi(v *int) *DeviceReadingUpdateOne {
	if v != nil {
		_u.SetAqi(*v)
	}
	return _u
}

// AddAqi adds value to the "aqi" field.
func (_u *DeviceReadingUpdateOne) AddAqi(v int) *DeviceReadingUpdateOne {
	_u.mutation.AddAqi(v)
	return _u
}

// SetTemperature sets the "temperature" field.
func (_u *DeviceReadingUpdateOne) SetTemperature(v float64) *DeviceReadingUpdateOne {
	_u.mutation.ResetTemperature()
	_u.mutation.SetTemperature(v)
	return _u
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_u *DeviceReadingUpdateOne) SetNillableTemperature(v *float64) *DeviceReadingUpdateOne {
	if v != nil {
		_u.SetTemperature(*v)
	}
	return _u
}

// AddTemperature adds value to the "temperature" field.
func (_u *DeviceReadingUpdateOne) AddTemperature(v float64) *DeviceReadingUpdateOne {
	_u.mutation.AddTemperature(v)
	return _u
}

// SetHumidity sets the "humidity" field.
func (_u *DeviceReadingUpdateOne) SetHumidity(v float64) *DeviceReadingUpdateOne {
	_u.mutation.ResetHumidity()
	_u.mutation.SetHumidity(v)
	return _u
}

// SetNillableHumidity sets the "humidity" field if the given value is not nil.
func (_u *DeviceReadingUpdateOne) SetNillableHumidity(v *float64) *DeviceReadingUpdateOne {
	if v != nil {
		_u.SetHumidity(*v)
	}
	return _u
}

// AddHumidity adds value to the "humidity" field.
func (_u *DeviceReadingUpdateOne) AddHumidity(v float64) *DeviceReadingUpdateOne {
	_u.mutation.AddHumidity(v)
	return _u
}

// SetHeatIndex sets the "heat_index" field.
func (_u *DeviceReadingUpdateOne) SetHeatIndex(v float64) *DeviceReadingUpdateOne {
	_u.mutation.ResetHeatIndex()
	_u.mutation.SetHeatIndex(v)
	return _u
}

// SetNillableHeatIndex sets the "heat_index" field if the given value is not nil.
func (_u *DeviceReadingUpdateOne) SetNillableHeatIndex(v *float64) *DeviceReadingUpdateOne {
	if v != nil {
		_u.SetHeatIndex(*v)
	}
	return _u
}

// AddHeatIndex adds value to the "heat_index" field.
func (_u *DeviceReadingUpdateOne) AddHeatIndex(v float64) *DeviceReadingUpdateOne {
	_u.mutation.AddHeatIndex(v)
	return _u
}

// SetTemperatureProvider sets the "temperature_provider" field.
func (_u *DeviceReadingUpdateOne) SetTemperatureProvider(v string) *DeviceReadingUpdateOne {
	_u.mutation.SetTemperatureProvider(v)
	return _u
}

// SetNillableTemperatureProvider sets the "temperature_provider" field if the given value is not nil.
func (_u *DeviceReadingUpdateOne) SetNillableTemperatureProvider(v *string) *DeviceReadingUpdateOne {
	if v != nil {
		_u.SetTemperatureProvider(*v)
	}
	return _u
}

// SetLat sets the "lat" field.
func (_u *DeviceReadingUpdateOne) SetLat(v float64) *DeviceReadingUpdateOne {
	_u.mutation.ResetLat()
	_u.mutation.SetLat(v)
	return _u
}

// SetNillableLat sets the "lat" field if the given value is not nil.
func (_u *DeviceReadingUpdateOne) SetNillableLat(v *float64) *DeviceReadingUpdateOne {
	if v != nil {
		_u.SetLat(*v)
	}
	return _u
}

// AddLat adds value to the "lat" field.
func (_u *DeviceReadingUpdateOne) AddLat(v float64) *DeviceReadingUpdateOne {
	_u.mutation.AddLat(v)
	return _u
}

// ClearLat clears the value of the "lat" field.
func (_u *DeviceReadingUpdateOne) ClearLat() *DeviceReadingUpdateOne {
	_u.mutation.ClearLat()
	return _u
}

// SetLon sets the "lon" field.
func (_u *DeviceReadingUpdateOne) SetLon(v float64) *DeviceReadingUpdateOne {
	_u.mutation.ResetLon()
	_u.mutation.SetLon(v)
	return _u
}

// SetNillableLon sets the "lon" field if the given value is not nil.
func (_u *DeviceReadingUpdateOne) SetNillableLon(v *float64) *DeviceReadingUpdateOne {
	if v != nil {
		_u.SetLon(*v)
	}
	return _u
}

// AddLon adds value to the "lon" field.
func (_u *DeviceReadingUpdateOne) AddLon(v float64) *DeviceReadingUpdateOne {
	_u.mutation.AddLon(v)
	return _u
}

// ClearLon clears the value of the "lon" field.
func (_u *DeviceReadingUpdateOne) ClearLon() *DeviceReadingUpdateOne {
	_u.mutation.ClearLon()
	return _u
}

// SetLocationProvider sets the "location_provider" field.
func (_u *DeviceReadingUpdateOne) SetLocationProvider(v string) *DeviceReadingUpdateOne {
	_u.mutation.SetLocationProvider(v)
	return _u
}

// SetNillableLocationProvider sets the "location_provider" field if the given value is not nil.
func (_u *DeviceReadingUpdateOne) SetNillableLocationProvider(v *string) *DeviceReadingUpdateOne {
	if v != nil {
		_u.SetLocationProvider(*v)
	}
	return _u
}

// ClearLocationProvider clears the value of the "location_provider" field.
func (_u *DeviceReadingUpdateOne) ClearLocationProvider() *DeviceReadingUpdateOne {
	_u.mutation.ClearLocationProvider()
	return _u
}

// Mutation returns the DeviceReadingMutation object of the builder.
func (_u *DeviceReadingUpdateOne) Mutation() *DeviceReadingMutation {
	return _u.mutation
}

// Where appends a list predicates to the DeviceReadingUpdate builder.
func (_u *DeviceReadingUpdateOne) Where(ps ...predicate.DeviceReading) *DeviceReadingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceReadingUpdateOne) Select(field string, fields ...string) *DeviceReadingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeviceReading entity.
func (_u *DeviceReadingUpdateOne) Save(ctx context.Context) (*DeviceReading, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceReadingUpdateOne) SaveX(ctx context.Context) *DeviceReading {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceReadingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceReadingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceReadingUpdateOne) check() error {
	if v, ok := _u.mutation.Pm10(); ok {
		if err := devicereading.Pm10Validator(v); err != nil {
			return &ValidationError{Name: "pm1_0", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.pm1_0": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pm25(); ok {
		if err := devicereading.Pm25Validator(v); err != nil {
			return &ValidationError{Name: "pm2_5", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.pm2_5": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pm100(); ok {
		if err := devicereading.Pm100Validator(v); err != nil {
			return &ValidationError{Name: "pm10_0", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.pm10_0": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PmsProvider(); ok {
		if err := devicereading.PmsProviderValidator(v); err != nil {
			return &ValidationError{Name: "pms_provider", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.pms_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Aqi(); ok {
		if err := devicereading.AqiValidator(v); err != nil {
			return &ValidationError{Name: "aqi", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.aqi": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Humidity(); ok {
		if err := devicereading.HumidityValidator(v); err != nil {
			return &ValidationError{Name: "humidity", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.humidity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TemperatureProvider(); ok {
		if err := devicereading.TemperatureProviderValidator(v); err != nil {
			return &ValidationError{Name: "temperature_provider", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.temperature_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Lat(); ok {
		if err := devicereading.LatValidator(v); err != nil {
			return &ValidationError{Name: "lat", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.lat": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Lon(); ok {
		if err := devicereading.LonValidator(v); err != nil {
			return &ValidationError{Name: "lon", err: fmt.Errorf(`ent: validator failed for field "DeviceReading.lon": %w`, err)}
		}
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DeviceReading.device"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeviceReadingUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeviceReadingUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeviceReadingUpdateOne) sqlSave(ctx context.Context) (_node *DeviceReading, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(devicereading.Table, devicereading.Columns, sqlgraph.NewFieldSpec(devicereading.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeviceReading.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, devicereading.FieldID)
		for _, f := range fields {
			if !devicereading.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != devicereading.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Pm10(); ok {
		_spec.SetField(devicereading.FieldPm10, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPm10(); ok {
		_spec.AddField(devicereading.FieldPm10, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Pm25(); ok {
		_spec.SetField(devicereading.FieldPm25, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPm25(); ok {
		_spec.AddField(devicereading.FieldPm25, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Pm100(); ok {
		_spec.SetField(devicereading.FieldPm100, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPm100(); ok {
		_spec.AddField(devicereading.FieldPm100, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PmsProvider(); ok {
		_spec.SetField(devicereading.FieldPmsProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Aqi(); ok {
		_spec.SetField(devicereading.FieldAqi, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAqi(); ok {
		_spec.AddField(devicereading.FieldAqi, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Temperature(); ok {
		_spec.SetField(devicereading.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTemperature(); ok {
		_spec.AddField(devicereading.FieldTemperature, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Humidity(); ok {
		_spec.SetField(devicereading.FieldHumidity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHumidity(); ok {
		_spec.AddField(devicereading.FieldHumidity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.HeatIndex(); ok {
		_spec.SetField(devicereading.FieldHeatIndex, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHeatIndex(); ok {
		_spec.AddField(devicereading.FieldHeatIndex, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TemperatureProvider(); ok {
		_spec.SetField(devicereading.FieldTemperatureProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Lat(); ok {
		_spec.SetField(devicereading.FieldLat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLat(); ok {
		_spec.AddField(devicereading.FieldLat, field.TypeFloat64, value)
	}
	if _u.mutation.LatCleared() {
		_spec.ClearField(devicereading.FieldLat, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Lon(); ok {
		_spec.SetField(devicereading.FieldLon, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLon(); ok {
		_spec.AddField(devicereading.FieldLon, field.TypeFloat64, value)
	}
	if _u.mutation.LonCleared() {
		_spec.ClearField(devicereading.FieldLon, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LocationProvider(); ok {
		_spec.SetField(devicereading.FieldLocationProvider, field.TypeString, value)
	}
	if _u.mutation.LocationProviderCleared() {
		_spec.ClearField(devicereading.FieldLocationProvider, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DeviceReading{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{devicereading.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
