// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-aiq-backend/internal/platform/ent/device"
	"go-aiq-backend/internal/platform/ent/devicereading"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// DeviceReading is the model entity for the DeviceReading schema.
type DeviceReading struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Internal id of the device that uploaded this reading
	DeviceID uuid.UUID `json:"device_id,omitempty"`
	// PM1.0 concentration (µg/m³)
	Pm10 float64 `json:"pm1_0"`
	// PM2.5 concentration (µg/m³)
	Pm25 float64 `json:"pm2_5"`
	// PM10 concentration (µg/m³)
	Pm100 float64 `json:"pm10_0"`
	// Particulate matter sensor model, e.g. "pms5003"
	PmsProvider string `json:"pms_provider,omitempty"`
	// Device-calculated Air Quality Index (US EPA scale; can exceed 500 in extreme pollution)
	Aqi int `json:"aqi,omitempty"`
	// Temperature (°C)
	Temperature float64 `json:"temperature,omitempty"`
	// Relative humidity (%)
	Humidity float64 `json:"humidity,omitempty"`
	// Heat index / feels-like temperature (°C)
	HeatIndex float64 `json:"heat_index,omitempty"`
	// Temperature sensor model, e.g. "dht22"
	TemperatureProvider string `json:"temperature_provider,omitempty"`
	// Latitude when the reading was taken; absent if no location fix
	Lat *float64 `json:"lat,omitempty"`
	// Longitude when the reading was taken; absent if no location fix
	Lon *float64 `json:"lon,omitempty"`
	// Source of the location fix, e.g. "mobile"; absent if no location fix
	LocationProvider string `json:"location_provider,omitempty"`
	// When the row was inserted
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeviceReadingQuery when eager-loading is set.
	Edges        DeviceReadingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeviceReadingEdges holds the relations/edges for other nodes in the graph.
type DeviceReadingEdges struct {
	// Device holds the value of the device edge.
	Device *Device `json:"device,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DeviceOrErr returns the Device value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeviceReadingEdges) DeviceOrErr() (*Device, error) {
	if e.Device != nil {
		return e.Device, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: device.Label}
	}
	return nil, &NotLoadedError{edge: "device"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeviceReading) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case devicereading.FieldPm10, devicereading.FieldPm25, devicereading.FieldPm100, devicereading.FieldTemperature, devicereading.FieldHumidity, devicereading.FieldHeatIndex, devicereading.FieldLat, devicereading.FieldLon:
			values[i] = new(sql.NullFloat64)
		case devicereading.FieldID, devicereading.FieldAqi:
			values[i] = new(sql.NullInt64)
		case devicereading.FieldPmsProvider, devicereading.FieldTemperatureProvider, devicereading.FieldLocationProvider:
			values[i] = new(sql.NullString)
		case devicereading.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case devicereading.FieldDeviceID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeviceReading fields.
func (_m *DeviceReading) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case devicereading.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case devicereading.FieldDeviceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value != nil {
				_m.DeviceID = *value
			}
		case devicereading.FieldPm10:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pm1_0", values[i])
			} else if value.Valid {
				_m.Pm10 = value.Float64
			}
		case devicereading.FieldPm25:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pm2_5", values[i])
			} else if value.Valid {
				_m.Pm25 = value.Float64
			}
		case devicereading.FieldPm100:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pm10_0", values[i])
			} else if value.Valid {
				_m.Pm100 = value.Float64
			}
		case devicereading.FieldPmsProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pms_provider", values[i])
			} else if value.Valid {
				_m.PmsProvider = value.String
			}
		case devicereading.FieldAqi:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field aqi", values[i])
			} else if value.Valid {
				_m.Aqi = int(value.Int64)
			}
		case devicereading.FieldTemperature:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field temperature", values[i])
			} else if value.Valid {
				_m.Temperature = value.Float64
			}
		case devicereading.FieldHumidity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field humidity", values[i])
			} else if value.Valid {
				_m.Humidity = value.Float64
			}
		case devicereading.FieldHeatIndex:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field heat_index", values[i])
			} else if value.Valid {
				_m.HeatIndex = value.Float64
			}
		case devicereading.FieldTemperatureProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field temperature_provider", values[i])
			} else if value.Valid {
				_m.TemperatureProvider = value.String
			}
		case devicereading.FieldLat:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field lat", values[i])
			} else if value.Valid {
				_m.Lat = new(float64)
				*_m.Lat = value.Float64
			}
		case devicereading.FieldLon:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field lon", values[i])
			} else if value.Valid {
				_m.Lon = new(float64)
				*_m.Lon = value.Float64
			}
		case devicereading.FieldLocationProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location_provider", values[i])
			} else if value.Valid {
				_m.LocationProvider = value.String
			}
		case devicereading.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeviceReading.
// This includes values selected through modifiers, order, etc.
func (_m *DeviceReading) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDevice queries the "device" edge of the DeviceReading entity.
func (_m *DeviceReading) QueryDevice() *DeviceQuery {
	return NewDeviceReadingClient(_m.config).QueryDevice(_m)
}

// Update returns a builder for updating this DeviceReading.
// Note that you need to call DeviceReading.Unwrap() before calling this method if this DeviceReading
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DeviceReading) Update() *DeviceReadingUpdateOne {
	return NewDeviceReadingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DeviceReading entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeviceReading) Unwrap() *DeviceReading {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeviceReading is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeviceReading) String() string {
	var builder strings.Builder
	builder.WriteString("DeviceReading(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("device_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeviceID))
	builder.WriteString(", ")
	builder.WriteString("pm1_0=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pm10))
	builder.WriteString(", ")
	builder.WriteString("pm2_5=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pm25))
	builder.WriteString(", ")
	builder.WriteString("pm10_0=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pm100))
	builder.WriteString(", ")
	builder.WriteString("pms_provider=")
	builder.WriteString(_m.PmsProvider)
	builder.WriteString(", ")
	builder.WriteString("aqi=")
	builder.WriteString(fmt.Sprintf("%v", _m.Aqi))
	builder.WriteString(", ")
	builder.WriteString("temperature=")
	builder.WriteString(fmt.Sprintf("%v", _m.Temperature))
	builder.WriteString(", ")
	builder.WriteString("humidity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Humidity))
	builder.WriteString(", ")
	builder.WriteString("heat_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.HeatIndex))
	builder.WriteString(", ")
	builder.WriteString("temperature_provider=")
	builder.WriteString(_m.TemperatureProvider)
	builder.WriteString(", ")
	if v := _m.Lat; v != nil {
		builder.WriteString("lat=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Lon; v != nil {
		builder.WriteString("lon=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("location_provider=")
	builder.WriteString(_m.LocationProvider)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeviceReadings is a parsable slice of DeviceReading.
type DeviceReadings []*DeviceReading
