// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-aiq-backend/internal/platform/ent/pmsreading"
	"go-aiq-backend/internal/platform/ent/predicate"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePMSReading = "PMSReading"
)

// PMSReadingMutation represents an operation that mutates the PMSReading nodes in the graph.
type PMSReadingMutation struct {
	config
	op            Op
	typ           string
	id            *int
	pm1_0         *float64
	addpm1_0      *float64
	pm2_5         *float64
	addpm2_5      *float64
	pm10_0        *float64
	addpm10_0     *float64
	aqi           *int
	addaqi        *int
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*PMSReading, error)
	predicates    []predicate.PMSReading
}

var _ ent.Mutation = (*PMSReadingMutation)(nil)

// pmsreadingOption allows management of the mutation configuration using functional options.
type pmsreadingOption func(*PMSReadingMutation)

// newPMSReadingMutation creates new mutation for the PMSReading entity.
func newPMSReadingMutation(c config, op Op, opts ...pmsreadingOption) *PMSReadingMutation {
	m := &PMSReadingMutation{
		config:        c,
		op:            op,
		typ:           TypePMSReading,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPMSReadingID sets the ID field of the mutation.
func withPMSReadingID(id int) pmsreadingOption {
	return func(m *PMSReadingMutation) {
		var (
			err   error
			once  sync.Once
			value *PMSReading
		)
		m.oldValue = func(ctx context.Context) (*PMSReading, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PMSReading.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPMSReading sets the old PMSReading of the mutation.
func withPMSReading(node *PMSReading) pmsreadingOption {
	return func(m *PMSReadingMutation) {
		m.oldValue = func(context.Context) (*PMSReading, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PMSReadingMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PMSReadingMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PMSReadingMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PMSReadingMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PMSReading.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetPm10 sets the "pm1_0" field.
func (m *PMSReadingMutation) SetPm10(f float64) {
	m.pm1_0 = &f
	m.addpm1_0 = nil
}

// Pm10 returns the value of the "pm1_0" field in the mutation.
func (m *PMSReadingMutation) Pm10() (r float64, exists bool) {
	v := m.pm1_0
	if v == nil {
		return
	}
	return *v, true
}

// OldPm10 returns the old "pm1_0" field's value of the PMSReading entity.
// If the PMSReading object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PMSReadingMutation) OldPm10(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPm10 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPm10 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPm10: %w", err)
	}
	return oldValue.Pm10, nil
}

// AddPm10 adds f to the "pm1_0" field.
func (m *PMSReadingMutation) AddPm10(f float64) {
	if m.addpm1_0 != nil {
		*m.addpm1_0 += f
	} else {
		m.addpm1_0 = &f
	}
}

// AddedPm10 returns the value that was added to the "pm1_0" field in this mutation.
func (m *PMSReadingMutation) AddedPm10() (r float64, exists bool) {
	v := m.addpm1_0
	if v == nil {
		return
	}
	return *v, true
}

// ResetPm10 resets all changes to the "pm1_0" field.
func (m *PMSReadingMutation) ResetPm10() {
	m.pm1_0 = nil
	m.addpm1_0 = nil
}

// SetPm25 sets the "pm2_5" field.
func (m *PMSReadingMutation) SetPm25(f float64) {
	m.pm2_5 = &f
	m.addpm2_5 = nil
}

// Pm25 returns the value of the "pm2_5" field in the mutation.
func (m *PMSReadingMutation) Pm25() (r float64, exists bool) {
	v := m.pm2_5
	if v == nil {
		return
	}
	return *v, true
}

// OldPm25 returns the old "pm2_5" field's value of the PMSReading entity.
// If the PMSReading object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PMSReadingMutation) OldPm25(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPm25 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPm25 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPm25: %w", err)
	}
	return oldValue.Pm25, nil
}

// AddPm25 adds f to the "pm2_5" field.
func (m *PMSReadingMutation) AddPm25(f float64) {
	if m.addpm2_5 != nil {
		*m.addpm2_5 += f
	} else {
		m.addpm2_5 = &f
	}
}

// AddedPm25 returns the value that was added to the "pm2_5" field in this mutation.
func (m *PMSReadingMutation) AddedPm25() (r float64, exists bool) {
	v := m.addpm2_5
	if v == nil {
		return
	}
	return *v, true
}

// ResetPm25 resets all changes to the "pm2_5" field.
func (m *PMSReadingMutation) ResetPm25() {
	m.pm2_5 = nil
	m.addpm2_5 = nil
}

// SetPm100 sets the "pm10_0" field.
func (m *PMSReadingMutation) SetPm100(f float64) {
	m.pm10_0 = &f
	m.addpm10_0 = nil
}

// Pm100 returns the value of the "pm10_0" field in the mutation.
func (m *PMSReadingMutation) Pm100() (r float64, exists bool) {
	v := m.pm10_0
	if v == nil {
		return
	}
	return *v, true
}

// OldPm100 returns the old "pm10_0" field's value of the PMSReading entity.
// If the PMSReading object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PMSReadingMutation) OldPm100(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPm100 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPm100 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPm100: %w", err)
	}
	return oldValue.Pm100, nil
}

// AddPm100 adds f to the "pm10_0" field.
func (m *PMSReadingMutation) AddPm100(f float64) {
	if m.addpm10_0 != nil {
		*m.addpm10_0 += f
	} else {
		m.addpm10_0 = &f
	}
}

// AddedPm100 returns the value that was added to the "pm10_0" field in this mutation.
func (m *PMSReadingMutation) AddedPm100() (r float64, exists bool) {
	v := m.addpm10_0
	if v == nil {
		return
	}
	return *v, true
}

// ResetPm100 resets all changes to the "pm10_0" field.
func (m *PMSReadingMutation) ResetPm100() {
	m.pm10_0 = nil
	m.addpm10_0 = nil
}

// SetAqi sets the "aqi" field.
func (m *PMSReadingMutation) SetAqi(i int) {
	m.aqi = &i
	m.addaqi = nil
}

// Aqi returns the value of the "aqi" field in the mutation.
func (m *PMSReadingMutation) Aqi() (r int, exists bool) {
	v := m.aqi
	if v == nil {
		return
	}
	return *v, true
}

// OldAqi returns the old "aqi" field's value of the PMSReading entity.
// If the PMSReading object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PMSReadingMutation) OldAqi(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAqi is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAqi requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAqi: %w", err)
	}
	return oldValue.Aqi, nil
}

// AddAqi adds i to the "aqi" field.
func (m *PMSReadingMutation) AddAqi(i int) {
	if m.addaqi != nil {
		*m.addaqi += i
	} else {
		m.addaqi = &i
	}
}

// AddedAqi returns the value that was added to the "aqi" field in this mutation.
func (m *PMSReadingMutation) AddedAqi() (r int, exists bool) {
	v := m.addaqi
	if v == nil {
		return
	}
	return *v, true
}

// ResetAqi resets all changes to the "aqi" field.
func (m *PMSReadingMutation) ResetAqi() {
	m.aqi = nil
	m.addaqi = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *PMSReadingMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PMSReadingMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the PMSReading entity.
// If the PMSReading object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PMSReadingMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PMSReadingMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the PMSReadingMutation builder.
func (m *PMSReadingMutation) Where(ps ...predicate.PMSReading) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PMSReadingMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PMSReadingMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PMSReading, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PMSReadingMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PMSReadingMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PMSReading).
func (m *PMSReadingMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PMSReadingMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.pm1_0 != nil {
		fields = append(fields, pmsreading.FieldPm10)
	}
	if m.pm2_5 != nil {
		fields = append(fields, pmsreading.FieldPm25)
	}
	if m.pm10_0 != nil {
		fields = append(fields, pmsreading.FieldPm100)
	}
	if m.aqi != nil {
		fields = append(fields, pmsreading.FieldAqi)
	}
	if m.created_at != nil {
		fields = append(fields, pmsreading.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PMSReadingMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pmsreading.FieldPm10:
		return m.Pm10()
	case pmsreading.FieldPm25:
		return m.Pm25()
	case pmsreading.FieldPm100:
		return m.Pm100()
	case pmsreading.FieldAqi:
		return m.Aqi()
	case pmsreading.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PMSReadingMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pmsreading.FieldPm10:
		return m.OldPm10(ctx)
	case pmsreading.FieldPm25:
		return m.OldPm25(ctx)
	case pmsreading.FieldPm100:
		return m.OldPm100(ctx)
	case pmsreading.FieldAqi:
		return m.OldAqi(ctx)
	case pmsreading.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown PMSReading field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PMSReadingMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pmsreading.FieldPm10:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPm10(v)
		return nil
	case pmsreading.FieldPm25:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPm25(v)
		return nil
	case pmsreading.FieldPm100:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPm100(v)
		return nil
	case pmsreading.FieldAqi:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAqi(v)
		return nil
	case pmsreading.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown PMSReading field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PMSReadingMutation) AddedFields() []string {
	var fields []string
	if m.addpm1_0 != nil {
		fields = append(fields, pmsreading.FieldPm10)
	}
	if m.addpm2_5 != nil {
		fields = append(fields, pmsreading.FieldPm25)
	}
	if m.addpm10_0 != nil {
		fields = append(fields, pmsreading.FieldPm100)
	}
	if m.addaqi != nil {
		fields = append(fields, pmsreading.FieldAqi)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PMSReadingMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case pmsreading.FieldPm10:
		return m.AddedPm10()
	case pmsreading.FieldPm25:
		return m.AddedPm25()
	case pmsreading.FieldPm100:
		return m.AddedPm100()
	case pmsreading.FieldAqi:
		return m.AddedAqi()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PMSReadingMutation) AddField(name string, value ent.Value) error {
	switch name {
	case pmsreading.FieldPm10:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPm10(v)
		return nil
	case pmsreading.FieldPm25:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPm25(v)
		return nil
	case pmsreading.FieldPm100:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPm100(v)
		return nil
	case pmsreading.FieldAqi:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAqi(v)
		return nil
	}
	return fmt.Errorf("unknown PMSReading numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PMSReadingMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PMSReadingMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PMSReadingMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PMSReading nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PMSReadingMutation) ResetField(name string) error {
	switch name {
	case pmsreading.FieldPm10:
		m.ResetPm10()
		return nil
	case pmsreading.FieldPm25:
		m.ResetPm25()
		return nil
	case pmsreading.FieldPm100:
		m.ResetPm100()
		return nil
	case pmsreading.FieldAqi:
		m.ResetAqi()
		return nil
	case pmsreading.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown PMSReading field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PMSReadingMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PMSReadingMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PMSReadingMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PMSReadingMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PMSReadingMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PMSReadingMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PMSReadingMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PMSReading unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PMSReadingMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PMSReading edge %s", name)
}
