// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-aiq-backend/internal/platform/ent/pmsreading"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PMSReading is the model entity for the PMSReading schema.
type PMSReading struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PM1.0 concentration (µg/m³)
	Pm10 float64 `json:"pm1_0"`
	// PM2.5 concentration (µg/m³)
	Pm25 float64 `json:"pm2_5"`
	// PM10 concentration (µg/m³)
	Pm100 float64 `json:"pm10_0"`
	// Calculated Air Quality Index (US EPA scale; can exceed 500 in extreme pollution)
	Aqi int `json:"aqi,omitempty"`
	// When the row was inserted
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PMSReading) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pmsreading.FieldPm10, pmsreading.FieldPm25, pmsreading.FieldPm100:
			values[i] = new(sql.NullFloat64)
		case pmsreading.FieldID, pmsreading.FieldAqi:
			values[i] = new(sql.NullInt64)
		case pmsreading.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PMSReading fields.
func (_m *PMSReading) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pmsreading.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pmsreading.FieldPm10:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pm1_0", values[i])
			} else if value.Valid {
				_m.Pm10 = value.Float64
			}
		case pmsreading.FieldPm25:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pm2_5", values[i])
			} else if value.Valid {
				_m.Pm25 = value.Float64
			}
		case pmsreading.FieldPm100:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pm10_0", values[i])
			} else if value.Valid {
				_m.Pm100 = value.Float64
			}
		case pmsreading.FieldAqi:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field aqi", values[i])
			} else if value.Valid {
				_m.Aqi = int(value.Int64)
			}
		case pmsreading.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PMSReading.
// This includes values selected through modifiers, order, etc.
func (_m *PMSReading) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PMSReading.
// Note that you need to call PMSReading.Unwrap() before calling this method if this PMSReading
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PMSReading) Update() *PMSReadingUpdateOne {
	return NewPMSReadingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PMSReading entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PMSReading) Unwrap() *PMSReading {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PMSReading is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PMSReading) String() string {
	var builder strings.Builder
	builder.WriteString("PMSReading(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("pm1_0=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pm10))
	builder.WriteString(", ")
	builder.WriteString("pm2_5=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pm25))
	builder.WriteString(", ")
	builder.WriteString("pm10_0=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pm100))
	builder.WriteString(", ")
	builder.WriteString("aqi=")
	builder.WriteString(fmt.Sprintf("%v", _m.Aqi))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PMSReadings is a parsable slice of PMSReading.
type PMSReadings []*PMSReading
