// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"go-aiq-backend/internal/platform/ent/pmsreading"
	"go-aiq-backend/internal/platform/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PMSReadingQuery is the builder for querying PMSReading entities.
type PMSReadingQuery struct {
	config
	ctx        *QueryContext
	order      []pmsreading.OrderOption
	inters     []Interceptor
	predicates []predicate.PMSReading
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PMSReadingQuery builder.
func (_q *PMSReadingQuery) Where(ps ...predicate.PMSReading) *PMSReadingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PMSReadingQuery) Limit(limit int) *PMSReadingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PMSReadingQuery) Offset(offset int) *PMSReadingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PMSReadingQuery) Unique(unique bool) *PMSReadingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PMSReadingQuery) Order(o ...pmsreading.OrderOption) *PMSReadingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first PMSReading entity from the query.
// Returns a *NotFoundError when no PMSReading was found.
func (_q *PMSReadingQuery) First(ctx context.Context) (*PMSReading, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pmsreading.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PMSReadingQuery) FirstX(ctx context.Context) *PMSReading {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PMSReading ID from the query.
// Returns a *NotFoundError when no PMSReading ID was found.
func (_q *PMSReadingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pmsreading.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PMSReadingQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PMSReading entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PMSReading entity is found.
// Returns a *NotFoundError when no PMSReading entities are found.
func (_q *PMSReadingQuery) Only(ctx context.Context) (*PMSReading, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pmsreading.Label}
	default:
		return nil, &NotSingularError{pmsreading.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PMSReadingQuery) OnlyX(ctx context.Context) *PMSReading {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PMSReading ID in the query.
// Returns a *NotSingularError when more than one PMSReading ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PMSReadingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pmsreading.Label}
	default:
		err = &NotSingularError{pmsreading.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PMSReadingQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PMSReadings.
func (_q *PMSReadingQuery) All(ctx context.Context) ([]*PMSReading, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PMSReading, *PMSReadingQuery]()
	return withInterceptors[[]*PMSReading](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PMSReadingQuery) AllX(ctx context.Context) []*PMSReading {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PMSReading IDs.
func (_q *PMSReadingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(pmsreading.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PMSReadingQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PMSReadingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PMSReadingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PMSReadingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PMSReadingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PMSReadingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PMSReadingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PMSReadingQuery) Clone() *PMSReadingQuery {
	if _q == nil {
		return nil
	}
	return &PMSReadingQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]pmsreading.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.PMSReading{}, _q.predicates...),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Pm10 float64 `json:"pm1_0"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PMSReading.Query().
//		GroupBy(pmsreading.FieldPm10).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PMSReadingQuery) GroupBy(field string, fields ...string) *PMSReadingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PMSReadingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = pmsreading.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Pm10 float64 `json:"pm1_0"`
//	}
//
//	client.PMSReading.Query().
//		Select(pmsreading.FieldPm10).
//		Scan(ctx, &v)
func (_q *PMSReadingQuery) Select(fields ...string) *PMSReadingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PMSReadingSelect{PMSReadingQuery: _q}
	sbuild.label = pmsreading.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PMSReadingSelect configured with the given aggregations.
func (_q *PMSReadingQuery) Aggregate(fns ...AggregateFunc) *PMSReadingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PMSReadingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !pmsreading.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PMSReadingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PMSReading, error) {
	var (
		nodes = []*PMSReading{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PMSReading).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PMSReading{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *PMSReadingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PMSReadingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pmsreading.Table, pmsreading.Columns, sqlgraph.NewFieldSpec(pmsreading.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pmsreading.FieldID)
		for i := range fields {
			if fields[i] != pmsreading.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PMSReadingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(pmsreading.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = pmsreading.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PMSReadingGroupBy is the group-by builder for PMSReading entities.
type PMSReadingGroupBy struct {
	selector
	build *PMSReadingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PMSReadingGroupBy) Aggregate(fns ...AggregateFunc) *PMSReadingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PMSReadingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PMSReadingQuery, *PMSReadingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PMSReadingGroupBy) sqlScan(ctx context.Context, root *PMSReadingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PMSReadingSelect is the builder for selecting fields of PMSReading entities.
type PMSReadingSelect struct {
	*PMSReadingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PMSReadingSelect) Aggregate(fns ...AggregateFunc) *PMSReadingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PMSReadingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PMSReadingQuery, *PMSReadingSelect](ctx, _s.PMSReadingQuery, _s, _s.inters, v)
}

func (_s *PMSReadingSelect) sqlScan(ctx context.Context, root *PMSReadingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
