// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-aiq-backend/internal/platform/ent/pmsreading"
	"go-aiq-backend/internal/platform/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PMSReadingUpdate is the builder for updating PMSReading entities.
type PMSReadingUpdate struct {
	config
	hooks    []Hook
	mutation *PMSReadingMutation
}

// Where appends a list predicates to the PMSReadingUpdate builder.
func (_u *PMSReadingUpdate) Where(ps ...predicate.PMSReading) *PMSReadingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPm10 sets the "pm1_0" field.
func (_u *PMSReadingUpdate) SetPm10(v float64) *PMSReadingUpdate {
	_u.mutation.ResetPm10()
	_u.mutation.SetPm10(v)
	return _u
}

// SetNillablePm10 sets the "pm1_0" field if the given value is not nil.
func (_u *PMSReadingUpdate) SetNillablePm10(v *float64) *PMSReadingUpdate {
	if v != nil {
		_u.SetPm10(*v)
	}
	return _u
}

// AddPm10 adds value to the "pm1_0" field.
func (_u *PMSReadingUpdate) AddPm10(v float64) *PMSReadingUpdate {
	_u.mutation.AddPm10(v)
	return _u
}

// SetPm25 sets the "pm2_5" field.
func (_u *PMSReadingUpdate) SetPm25(v float64) *PMSReadingUpdate {
	_u.mutation.ResetPm25()
	_u.mutation.SetPm25(v)
	return _u
}

// SetNillablePm25 sets the "pm2_5" field if the given value is not nil.
func (_u *PMSReadingUpdate) SetNillablePm25(v *float64) *PMSReadingUpdate {
	if v != nil {
		_u.SetPm25(*v)
	}
	return _u
}

// AddPm25 adds value to the "pm2_5" field.
func (_u *PMSReadingUpdate) AddPm25(v float64) *PMSReadingUpdate {
	_u.mutation.AddPm25(v)
	return _u
}

// SetPm100 sets the "pm10_0" field.
func (_u *PMSReadingUpdate) SetPm100(v float64) *PMSReadingUpdate {
	_u.mutation.ResetPm100()
	_u.mutation.SetPm100(v)
	return _u
}

// SetNillablePm100 sets the "pm10_0" field if the given value is not nil.
func (_u *PMSReadingUpdate) SetNillablePm100(v *float64) *PMSReadingUpdate {
	if v != nil {
		_u.SetPm100(*v)
	}
	return _u
}

// AddPm100 adds value to the "pm10_0" field.
func (_u *PMSReadingUpdate) AddPm100(v float64) *PMSReadingUpdate {
	_u.mutation.AddPm100(v)
	return _u
}

// SetAqi sets the "aqi" field.
func (_u *PMSReadingUpdate) SetAqi(v int) *PMSReadingUpdate {
	_u.mutation.ResetAqi()
	_u.mutation.SetAqi(v)
	return _u
}

// SetNillableAqi sets the "aqi" field if the given value is not nil.
func (_u *PMSReadingUpdate) SetNillableAqi(v *int) *PMSReadingUpdate {
	if v != nil {
		_u.SetAqi(*v)
	}
	return _u
}

// AddAqi adds value to the "aqi" field.
func (_u *PMSReadingUpdate) AddAqi(v int) *PMSReadingUpdate {
	_u.mutation.AddAqi(v)
	return _u
}

// Mutation returns the PMSReadingMutation object of the builder.
func (_u *PMSReadingUpdate) Mutation() *PMSReadingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PMSReadingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PMSReadingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PMSReadingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PMSReadingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PMSReadingUpdate) check() error {
	if v, ok := _u.mutation.Pm10(); ok {
		if err := pmsreading.Pm10Validator(v); err != nil {
			return &ValidationError{Name: "pm1_0", err: fmt.Errorf(`ent: validator failed for field "PMSReading.pm1_0": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pm25(); ok {
		if err := pmsreading.Pm25Validator(v); err != nil {
			return &ValidationError{Name: "pm2_5", err: fmt.Errorf(`ent: validator failed for field "PMSReading.pm2_5": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pm100(); ok {
		if err := pmsreading.Pm100Validator(v); err != nil {
			return &ValidationError{Name: "pm10_0", err: fmt.Errorf(`ent: validator failed for field "PMSReading.pm10_0": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Aqi(); ok {
		if err := pmsreading.AqiValidator(v); err != nil {
			return &ValidationError{Name: "aqi", err: fmt.Errorf(`ent: validator failed for field "PMSReading.aqi": %w`, err)}
		}
	}
	return nil
}

func (_u *PMSReadingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pmsreading.Table, pmsreading.Columns, sqlgraph.NewFieldSpec(pmsreading.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Pm10(); ok {
		_spec.SetField(pmsreading.FieldPm10, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPm10(); ok {
		_spec.AddField(pmsreading.FieldPm10, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Pm25(); ok {
		_spec.SetField(pmsreading.FieldPm25, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPm25(); ok {
		_spec.AddField(pmsreading.FieldPm25, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Pm100(); ok {
		_spec.SetField(pmsreading.FieldPm100, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPm100(); ok {
		_spec.AddField(pmsreading.FieldPm100, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Aqi(); ok {
		_spec.SetField(pmsreading.FieldAqi, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAqi(); ok {
		_spec.AddField(pmsreading.FieldAqi, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pmsreading.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PMSReadingUpdateOne is the builder for updating a single PMSReading entity.
type PMSReadingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PMSReadingMutation
}

// SetPm10 sets the "pm1_0" field.
func (_u *PMSReadingUpdateOne) SetPm10(v float64) *PMSReadingUpdateOne {
	_u.mutation.ResetPm10()
	_u.mutation.SetPm10(v)
	return _u
}

// SetNillablePm10 sets the "pm1_0" field if the given value is not nil.
func (_u *PMSReadingUpdateOne) SetNillablePm10(v *float64) *PMSReadingUpdateOne {
	if v != nil {
		_u.SetPm10(*v)
	}
	return _u
}

// AddPm10 adds value to the "pm1_0" field.
func (_u *PMSReadingUpdateOne) AddPm10(v float64) *PMSReadingUpdateOne {
	_u.mutation.AddPm10(v)
	return _u
}

// SetPm25 sets the "pm2_5" field.
func (_u *PMSReadingUpdateOne) SetPm25(v float64) *PMSReadingUpdateOne {
	_u.mutation.ResetPm25()
	_u.mutation.SetPm25(v)
	return _u
}

// SetNillablePm25 sets the "pm2_5" field if the given value is not nil.
func (_u *PMSReadingUpdateOne) SetNillablePm25(v *float64) *PMSReadingUpdateOne {
	if v != nil {
		_u.SetPm25(*v)
	}
	return _u
}

// AddPm25 adds value to the "pm2_5" field.
func (_u *PMSReadingUpdateOne) AddPm25(v float64) *PMSReadingUpdateOne {
	_u.mutation.AddPm25(v)
	return _u
}

// SetPm100 sets the "pm10_0" field.
func (_u *PMSReadingUpdateOne) SetPm100(v float64) *PMSReadingUpdateOne {
	_u.mutation.ResetPm100()
	_u.mutation.SetPm100(v)
	return _u
}

// SetNillablePm100 sets the "pm10_0" field if the given value is not nil.
func (_u *PMSReadingUpdateOne) SetNillablePm100(v *float64) *PMSReadingUpdateOne {
	if v != nil {
		_u.SetPm100(*v)
	}
	return _u
}

// AddPm100 adds value to the "pm10_0" field.
func (_u *PMSReadingUpdateOne) AddPm100(v float64) *PMSReadingUpdateOne {
	_u.mutation.AddPm100(v)
	return _u
}

// SetAqi sets the "aqi" field.
func (_u *PMSReadingUpdateOne) SetAqi(v int) *PMSReadingUpdateOne {
	_u.mutation.ResetAqi()
	_u.mutation.SetAqi(v)
	return _u
}

// SetNillableAqi sets the "aqi" field if the given value is not nil.
func (_u *PMSReadingUpdateOne) SetNillableAqi(v *int) *PMSReadingUpdateOne {
	if v != nil {
		_u.SetAqi(*v)
	}
	return _u
}

// AddAqi adds value to the "aqi" field.
func (_u *PMSReadingUpdateOne) AddAqi(v int) *PMSReadingUpdateOne {
	_u.mutation.AddAqi(v)
	return _u
}

// Mutation returns the PMSReadingMutation object of the builder.
func (_u *PMSReadingUpdateOne) Mutation() *PMSReadingMutation {
	return _u.mutation
}

// Where appends a list predicates to the PMSReadingUpdate builder.
func (_u *PMSReadingUpdateOne) Where(ps ...predicate.PMSReading) *PMSReadingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PMSReadingUpdateOne) Select(field string, fields ...string) *PMSReadingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PMSReading entity.
func (_u *PMSReadingUpdateOne) Save(ctx context.Context) (*PMSReading, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PMSReadingUpdateOne) SaveX(ctx context.Context) *PMSReading {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PMSReadingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PMSReadingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PMSReadingUpdateOne) check() error {
	if v, ok := _u.mutation.Pm10(); ok {
		if err := pmsreading.Pm10Validator(v); err != nil {
			return &ValidationError{Name: "pm1_0", err: fmt.Errorf(`ent: validator failed for field "PMSReading.pm1_0": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pm25(); ok {
		if err := pmsreading.Pm25Validator(v); err != nil {
			return &ValidationError{Name: "pm2_5", err: fmt.Errorf(`ent: validator failed for field "PMSReading.pm2_5": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pm100(); ok {
		if err := pmsreading.Pm100Validator(v); err != nil {
			return &ValidationError{Name: "pm10_0", err: fmt.Errorf(`ent: validator failed for field "PMSReading.pm10_0": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Aqi(); ok {
		if err := pmsreading.AqiValidator(v); err != nil {
			return &ValidationError{Name: "aqi", err: fmt.Errorf(`ent: validator failed for field "PMSReading.aqi": %w`, err)}
		}
	}
	return nil
}

func (_u *PMSReadingUpdateOne) sqlSave(ctx context.Context) (_node *PMSReading, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pmsreading.Table, pmsreading.Columns, sqlgraph.NewFieldSpec(pmsreading.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PMSReading.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pmsreading.FieldID)
		for _, f := range fields {
			if !pmsreading.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pmsreading.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Pm10(); ok {
		_spec.SetField(pmsreading.FieldPm10, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPm10(); ok {
		_spec.AddField(pmsreading.FieldPm10, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Pm25(); ok {
		_spec.SetField(pmsreading.FieldPm25, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPm25(); ok {
		_spec.AddField(pmsreading.FieldPm25, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Pm100(); ok {
		_spec.SetField(pmsreading.FieldPm100, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPm100(); ok {
		_spec.AddField(pmsreading.FieldPm100, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Aqi(); ok {
		_spec.SetField(pmsreading.FieldAqi, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAqi(); ok {
		_spec.AddField(pmsreading.FieldAqi, field.TypeInt, value)
	}
	_node = &PMSReading{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pmsreading.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
