// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-aiq-backend/internal/platform/ent/pmsreading"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PMSReadingCreate is the builder for creating a PMSReading entity.
type PMSReadingCreate struct {
	config
	mutation *PMSReadingMutation
	hooks    []Hook
}

// SetPm10 sets the "pm1_0" field.
func (_c *PMSReadingCreate) SetPm10(v float64) *PMSReadingCreate {
	_c.mutation.SetPm10(v)
	return _c
}

// SetPm25 sets the "pm2_5" field.
func (_c *PMSReadingCreate) SetPm25(v float64) *PMSReadingCreate {
	_c.mutation.SetPm25(v)
	return _c
}

// SetPm100 sets the "pm10_0" field.
func (_c *PMSReadingCreate) SetPm100(v float64) *PMSReadingCreate {
	_c.mutation.SetPm100(v)
	return _c
}

// SetAqi sets the "aqi" field.
func (_c *PMSReadingCreate) SetAqi(v int) *PMSReadingCreate {
	_c.mutation.SetAqi(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PMSReadingCreate) SetCreatedAt(v time.Time) *PMSReadingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PMSReadingCreate) SetNillableCreatedAt(v *time.Time) *PMSReadingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the PMSReadingMutation object of the builder.
func (_c *PMSReadingCreate) Mutation() *PMSReadingMutation {
	return _c.mutation
}

// Save creates the PMSReading in the database.
func (_c *PMSReadingCreate) Save(ctx context.Context) (*PMSReading, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PMSReadingCreate) SaveX(ctx context.Context) *PMSReading {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PMSReadingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PMSReadingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PMSReadingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pmsreading.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PMSReadingCreate) check() error {
	if _, ok := _c.mutation.Pm10(); !ok {
		return &ValidationError{Name: "pm1_0", err: errors.New(`ent: missing required field "PMSReading.pm1_0"`)}
	}
	if v, ok := _c.mutation.Pm10(); ok {
		if err := pmsreading.Pm10Validator(v); err != nil {
			return &ValidationError{Name: "pm1_0", err: fmt.Errorf(`ent: validator failed for field "PMSReading.pm1_0": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Pm25(); !ok {
		return &ValidationError{Name: "pm2_5", err: errors.New(`ent: missing required field "PMSReading.pm2_5"`)}
	}
	if v, ok := _c.mutation.Pm25(); ok {
		if err := pmsreading.Pm25Validator(v); err != nil {
			return &ValidationError{Name: "pm2_5", err: fmt.Errorf(`ent: validator failed for field "PMSReading.pm2_5": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Pm100(); !ok {
		return &ValidationError{Name: "pm10_0", err: errors.New(`ent: missing required field "PMSReading.pm10_0"`)}
	}
	if v, ok := _c.mutation.Pm100(); ok {
		if err := pmsreading.Pm100Validator(v); err != nil {
			return &ValidationError{Name: "pm10_0", err: fmt.Errorf(`ent: validator failed for field "PMSReading.pm10_0": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Aqi(); !ok {
		return &ValidationError{Name: "aqi", err: errors.New(`ent: missing required field "PMSReading.aqi"`)}
	}
	if v, ok := _c.mutation.Aqi(); ok {
		if err := pmsreading.AqiValidator(v); err != nil {
			return &ValidationError{Name: "aqi", err: fmt.Errorf(`ent: validator failed for field "PMSReading.aqi": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PMSReading.created_at"`)}
	}
	return nil
}

func (_c *PMSReadingCreate) sqlSave(ctx context.Context) (*PMSReading, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PMSReadingCreate) createSpec() (*PMSReading, *sqlgraph.CreateSpec) {
	var (
		_node = &PMSReading{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pmsreading.Table, sqlgraph.NewFieldSpec(pmsreading.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Pm10(); ok {
		_spec.SetField(pmsreading.FieldPm10, field.TypeFloat64, value)
		_node.Pm10 = value
	}
	if value, ok := _c.mutation.Pm25(); ok {
		_spec.SetField(pmsreading.FieldPm25, field.TypeFloat64, value)
		_node.Pm25 = value
	}
	if value, ok := _c.mutation.Pm100(); ok {
		_spec.SetField(pmsreading.FieldPm100, field.TypeFloat64, value)
		_node.Pm100 = value
	}
	if value, ok := _c.mutation.Aqi(); ok {
		_spec.SetField(pmsreading.FieldAqi, field.TypeInt, value)
		_node.Aqi = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pmsreading.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// PMSReadingCreateBulk is the builder for creating many PMSReading entities in bulk.
type PMSReadingCreateBulk struct {
	config
	err      error
	builders []*PMSReadingCreate
}

// Save creates the PMSReading entities in the database.
func (_c *PMSReadingCreateBulk) Save(ctx context.Context) ([]*PMSReading, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PMSReading, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PMSReadingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PMSReadingCreateBulk) SaveX(ctx context.Context) []*PMSReading {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PMSReadingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PMSReadingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
