// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-aiq-backend/internal/platform/ent/pmsreading"
	"go-aiq-backend/internal/platform/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pmsreadingFields := schema.PMSReading{}.Fields()
	_ = pmsreadingFields
	// pmsreadingDescPm10 is the schema descriptor for pm1_0 field.
	pmsreadingDescPm10 := pmsreadingFields[0].Descriptor()
	// pmsreading.Pm10Validator is a validator for the "pm1_0" field. It is called by the builders before save.
	pmsreading.Pm10Validator = pmsreadingDescPm10.Validators[0].(func(float64) error)
	// pmsreadingDescPm25 is the schema descriptor for pm2_5 field.
	pmsreadingDescPm25 := pmsreadingFields[1].Descriptor()
	// pmsreading.Pm25Validator is a validator for the "pm2_5" field. It is called by the builders before save.
	pmsreading.Pm25Validator = pmsreadingDescPm25.Validators[0].(func(float64) error)
	// pmsreadingDescPm100 is the schema descriptor for pm10_0 field.
	pmsreadingDescPm100 := pmsreadingFields[2].Descriptor()
	// pmsreading.Pm100Validator is a validator for the "pm10_0" field. It is called by the builders before save.
	pmsreading.Pm100Validator = pmsreadingDescPm100.Validators[0].(func(float64) error)
	// pmsreadingDescAqi is the schema descriptor for aqi field.
	pmsreadingDescAqi := pmsreadingFields[3].Descriptor()
	// pmsreading.AqiValidator is a validator for the "aqi" field. It is called by the builders before save.
	pmsreading.AqiValidator = pmsreadingDescAqi.Validators[0].(func(int) error)
	// pmsreadingDescCreatedAt is the schema descriptor for created_at field.
	pmsreadingDescCreatedAt := pmsreadingFields[4].Descriptor()
	// pmsreading.DefaultCreatedAt holds the default value on creation for the created_at field.
	pmsreading.DefaultCreatedAt = pmsreadingDescCreatedAt.Default.(func() time.Time)
}
