// Code generated by ent, DO NOT EDIT.

package devicereading

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the devicereading type in the database.
	Label = "device_reading"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldPm10 holds the string denoting the pm1_0 field in the database.
	FieldPm10 = "pm1_0"
	// FieldPm25 holds the string denoting the pm2_5 field in the database.
	FieldPm25 = "pm2_5"
	// FieldPm100 holds the string denoting the pm10_0 field in the database.
	FieldPm100 = "pm10_0"
	// FieldPmsProvider holds the string denoting the pms_provider field in the database.
	FieldPmsProvider = "pms_provider"
	// FieldAqi holds the string denoting the aqi field in the database.
	FieldAqi = "aqi"
	// FieldTemperature holds the string denoting the temperature field in the database.
	FieldTemperature = "temperature"
	// FieldHumidity holds the string denoting the humidity field in the database.
	FieldHumidity = "humidity"
	// FieldHeatIndex holds the string denoting the heat_index field in the database.
	FieldHeatIndex = "heat_index"
	// FieldTemperatureProvider holds the string denoting the temperature_provider field in the database.
	FieldTemperatureProvider = "temperature_provider"
	// FieldLat holds the string denoting the lat field in the database.
	FieldLat = "lat"
	// FieldLon holds the string denoting the lon field in the database.
	FieldLon = "lon"
	// FieldLocationProvider holds the string denoting the location_provider field in the database.
	FieldLocationProvider = "location_provider"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeDevice holds the string denoting the device edge name in mutations.
	EdgeDevice = "device"
	// Table holds the table name of the devicereading in the database.
	Table = "device_readings"
	// DeviceTable is the table that holds the device relation/edge.
	DeviceTable = "device_readings"
	// DeviceInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DeviceInverseTable = "devices"
	// DeviceColumn is the table column denoting the device relation/edge.
	DeviceColumn = "device_id"
)

// Columns holds all SQL columns for devicereading fields.
var Columns = []string{
	FieldID,
	FieldDeviceID,
	FieldPm10,
	FieldPm25,
	FieldPm100,
	FieldPmsProvider,
	FieldAqi,
	FieldTemperature,
	FieldHumidity,
	FieldHeatIndex,
	FieldTemperatureProvider,
	FieldLat,
	FieldLon,
	FieldLocationProvider,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// Pm10Validator is a validator for the "pm1_0" field. It is called by the builders before save.
	Pm10Validator func(float64) error
	// Pm25Validator is a validator for the "pm2_5" field. It is called by the builders before save.
	Pm25Validator func(float64) error
	// Pm100Validator is a validator for the "pm10_0" field. It is called by the builders before save.
	Pm100Validator func(float64) error
	// PmsProviderValidator is a validator for the "pms_provider" field. It is called by the builders before save.
	PmsProviderValidator func(string) error
	// AqiValidator is a validator for the "aqi" field. It is called by the builders before save.
	AqiValidator func(int) error
	// HumidityValidator is a validator for the "humidity" field. It is called by the builders before save.
	HumidityValidator func(float64) error
	// TemperatureProviderValidator is a validator for the "temperature_provider" field. It is called by the builders before save.
	TemperatureProviderValidator func(string) error
	// LatValidator is a validator for the "lat" field. It is called by the builders before save.
	LatValidator func(float64) error
	// LonValidator is a validator for the "lon" field. It is called by the builders before save.
	LonValidator func(float64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the DeviceReading queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByPm10 orders the results by the pm1_0 field.
func ByPm10(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPm10, opts...).ToFunc()
}

// ByPm25 orders the results by the pm2_5 field.
func ByPm25(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPm25, opts...).ToFunc()
}

// ByPm100 orders the results by the pm10_0 field.
func ByPm100(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPm100, opts...).ToFunc()
}

// ByPmsProvider orders the results by the pms_provider field.
func ByPmsProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPmsProvider, opts...).ToFunc()
}

// ByAqi orders the results by the aqi field.
func ByAqi(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAqi, opts...).ToFunc()
}

// ByTemperature orders the results by the temperature field.
func ByTemperature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemperature, opts...).ToFunc()
}

// ByHumidity orders the results by the humidity field.
func ByHumidity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHumidity, opts...).ToFunc()
}

// ByHeatIndex orders the results by the heat_index field.
func ByHeatIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeatIndex, opts...).ToFunc()
}

// ByTemperatureProvider orders the results by the temperature_provider field.
func ByTemperatureProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemperatureProvider, opts...).ToFunc()
}

// ByLat orders the results by the lat field.
func ByLat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLat, opts...).ToFunc()
}

// ByLon orders the results by the lon field.
func ByLon(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLon, opts...).ToFunc()
}

// ByLocationProvider orders the results by the location_provider field.
func ByLocationProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocationProvider, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDeviceField orders the results by device field.
func ByDeviceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeviceStep(), sql.OrderByField(field, opts...))
	}
}
func newDeviceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeviceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
	)
}
