// Code generated by ent, DO NOT EDIT.

package devicereading

import (
	"go-aiq-backend/internal/platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldID, id))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v uuid.UUID) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldDeviceID, v))
}

// Pm10 applies equality check predicate on the "pm1_0" field. It's identical to Pm10EQ.
func Pm10(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldPm10, v))
}

// Pm25 applies equality check predicate on the "pm2_5" field. It's identical to Pm25EQ.
func Pm25(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldPm25, v))
}

// Pm100 applies equality check predicate on the "pm10_0" field. It's identical to Pm100EQ.
func Pm100(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldPm100, v))
}

// PmsProvider applies equality check predicate on the "pms_provider" field. It's identical to PmsProviderEQ.
func PmsProvider(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldPmsProvider, v))
}

// Aqi applies equality check predicate on the "aqi" field. It's identical to AqiEQ.
func Aqi(v int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldAqi, v))
}

// Temperature applies equality check predicate on the "temperature" field. It's identical to TemperatureEQ.
func Temperature(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldTemperature, v))
}

// Humidity applies equality check predicate on the "humidity" field. It's identical to HumidityEQ.
func Humidity(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldHumidity, v))
}

// HeatIndex applies equality check predicate on the "heat_index" field. It's identical to HeatIndexEQ.
func HeatIndex(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldHeatIndex, v))
}

// TemperatureProvider applies equality check predicate on the "temperature_provider" field. It's identical to TemperatureProviderEQ.
func TemperatureProvider(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldTemperatureProvider, v))
}

// Lat applies equality check predicate on the "lat" field. It's identical to LatEQ.
func Lat(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldLat, v))
}

// Lon applies equality check predicate on the "lon" field. It's identical to LonEQ.
func Lon(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldLon, v))
}

// LocationProvider applies equality check predicate on the "location_provider" field. It's identical to LocationProviderEQ.
func LocationProvider(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldLocationProvider, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldCreatedAt, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v uuid.UUID) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v uuid.UUID) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...uuid.UUID) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...uuid.UUID) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldDeviceID, vs...))
}

// Pm10EQ applies the EQ predicate on the "pm1_0" field.
func Pm10EQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldPm10, v))
}

// Pm10NEQ applies the NEQ predicate on the "pm1_0" field.
func Pm10NEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldPm10, v))
}

// Pm10In applies the In predicate on the "pm1_0" field.
func Pm10In(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldPm10, vs...))
}

// Pm10NotIn applies the NotIn predicate on the "pm1_0" field.
func Pm10NotIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldPm10, vs...))
}

// Pm10GT applies the GT predicate on the "pm1_0" field.
func Pm10GT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldPm10, v))
}

// Pm10GTE applies the GTE predicate on the "pm1_0" field.
func Pm10GTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldPm10, v))
}

// Pm10LT applies the LT predicate on the "pm1_0" field.
func Pm10LT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldPm10, v))
}

// Pm10LTE applies the LTE predicate on the "pm1_0" field.
func Pm10LTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldPm10, v))
}

// Pm25EQ applies the EQ predicate on the "pm2_5" field.
func Pm25EQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldPm25, v))
}

// Pm25NEQ applies the NEQ predicate on the "pm2_5" field.
func Pm25NEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldPm25, v))
}

// Pm25In applies the In predicate on the "pm2_5" field.
func Pm25In(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldPm25, vs...))
}

// Pm25NotIn applies the NotIn predicate on the "pm2_5" field.
func Pm25NotIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldPm25, vs...))
}

// Pm25GT applies the GT predicate on the "pm2_5" field.
func Pm25GT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldPm25, v))
}

// Pm25GTE applies the GTE predicate on the "pm2_5" field.
func Pm25GTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldPm25, v))
}

// Pm25LT applies the LT predicate on the "pm2_5" field.
func Pm25LT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldPm25, v))
}

// Pm25LTE applies the LTE predicate on the "pm2_5" field.
func Pm25LTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldPm25, v))
}

// Pm100EQ applies the EQ predicate on the "pm10_0" field.
func Pm100EQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldPm100, v))
}

// Pm100NEQ applies the NEQ predicate on the "pm10_0" field.
func Pm100NEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldPm100, v))
}

// Pm100In applies the In predicate on the "pm10_0" field.
func Pm100In(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldPm100, vs...))
}

// Pm100NotIn applies the NotIn predicate on the "pm10_0" field.
func Pm100NotIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldPm100, vs...))
}

// Pm100GT applies the GT predicate on the "pm10_0" field.
func Pm100GT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldPm100, v))
}

// Pm100GTE applies the GTE predicate on the "pm10_0" field.
func Pm100GTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldPm100, v))
}

// Pm100LT applies the LT predicate on the "pm10_0" field.
func Pm100LT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldPm100, v))
}

// Pm100LTE applies the LTE predicate on the "pm10_0" field.
func Pm100LTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldPm100, v))
}

// PmsProviderEQ applies the EQ predicate on the "pms_provider" field.
func PmsProviderEQ(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldPmsProvider, v))
}

// PmsProviderNEQ applies the NEQ predicate on the "pms_provider" field.
func PmsProviderNEQ(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldPmsProvider, v))
}

// PmsProviderIn applies the In predicate on the "pms_provider" field.
func PmsProviderIn(vs ...string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldPmsProvider, vs...))
}

// PmsProviderNotIn applies the NotIn predicate on the "pms_provider" field.
func PmsProviderNotIn(vs ...string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldPmsProvider, vs...))
}

// PmsProviderGT applies the GT predicate on the "pms_provider" field.
func PmsProviderGT(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldPmsProvider, v))
}

// PmsProviderGTE applies the GTE predicate on the "pms_provider" field.
func PmsProviderGTE(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldPmsProvider, v))
}

// PmsProviderLT applies the LT predicate on the "pms_provider" field.
func PmsProviderLT(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldPmsProvider, v))
}

// PmsProviderLTE applies the LTE predicate on the "pms_provider" field.
func PmsProviderLTE(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldPmsProvider, v))
}

// PmsProviderContains applies the Contains predicate on the "pms_provider" field.
func PmsProviderContains(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldContains(FieldPmsProvider, v))
}

// PmsProviderHasPrefix applies the HasPrefix predicate on the "pms_provider" field.
func PmsProviderHasPrefix(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldHasPrefix(FieldPmsProvider, v))
}

// PmsProviderHasSuffix applies the HasSuffix predicate on the "pms_provider" field.
func PmsProviderHasSuffix(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldHasSuffix(FieldPmsProvider, v))
}

// PmsProviderEqualFold applies the EqualFold predicate on the "pms_provider" field.
func PmsProviderEqualFold(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEqualFold(FieldPmsProvider, v))
}

// PmsProviderContainsFold applies the ContainsFold predicate on the "pms_provider" field.
func PmsProviderContainsFold(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldContainsFold(FieldPmsProvider, v))
}

// AqiEQ applies the EQ predicate on the "aqi" field.
func AqiEQ(v int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldAqi, v))
}

// AqiNEQ applies the NEQ predicate on the "aqi" field.
func AqiNEQ(v int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldAqi, v))
}

// AqiIn applies the In predicate on the "aqi" field.
func AqiIn(vs ...int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldAqi, vs...))
}

// AqiNotIn applies the NotIn predicate on the "aqi" field.
func AqiNotIn(vs ...int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldAqi, vs...))
}

// AqiGT applies the GT predicate on the "aqi" field.
func AqiGT(v int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldAqi, v))
}

// AqiGTE applies the GTE predicate on the "aqi" field.
func AqiGTE(v int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldAqi, v))
}

// AqiLT applies the LT predicate on the "aqi" field.
func AqiLT(v int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldAqi, v))
}

// AqiLTE applies the LTE predicate on the "aqi" field.
func AqiLTE(v int) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldAqi, v))
}

// TemperatureEQ applies the EQ predicate on the "temperature" field.
func TemperatureEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldTemperature, v))
}

// TemperatureNEQ applies the NEQ predicate on the "temperature" field.
func TemperatureNEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldTemperature, v))
}

// TemperatureIn applies the In predicate on the "temperature" field.
func TemperatureIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldTemperature, vs...))
}

// TemperatureNotIn applies the NotIn predicate on the "temperature" field.
func TemperatureNotIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldTemperature, vs...))
}

// TemperatureGT applies the GT predicate on the "temperature" field.
func TemperatureGT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldTemperature, v))
}

// TemperatureGTE applies the GTE predicate on the "temperature" field.
func TemperatureGTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldTemperature, v))
}

// TemperatureLT applies the LT predicate on the "temperature" field.
func TemperatureLT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldTemperature, v))
}

// TemperatureLTE applies the LTE predicate on the "temperature" field.
func TemperatureLTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldTemperature, v))
}

// HumidityEQ applies the EQ predicate on the "humidity" field.
func HumidityEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldHumidity, v))
}

// HumidityNEQ applies the NEQ predicate on the "humidity" field.
func HumidityNEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldHumidity, v))
}

// HumidityIn applies the In predicate on the "humidity" field.
func HumidityIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldHumidity, vs...))
}

// HumidityNotIn applies the NotIn predicate on the "humidity" field.
func HumidityNotIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldHumidity, vs...))
}

// HumidityGT applies the GT predicate on the "humidity" field.
func HumidityGT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldHumidity, v))
}

// HumidityGTE applies the GTE predicate on the "humidity" field.
func HumidityGTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldHumidity, v))
}

// HumidityLT applies the LT predicate on the "humidity" field.
func HumidityLT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldHumidity, v))
}

// HumidityLTE applies the LTE predicate on the "humidity" field.
func HumidityLTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldHumidity, v))
}

// HeatIndexEQ applies the EQ predicate on the "heat_index" field.
func HeatIndexEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldHeatIndex, v))
}

// HeatIndexNEQ applies the NEQ predicate on the "heat_index" field.
func HeatIndexNEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldHeatIndex, v))
}

// HeatIndexIn applies the In predicate on the "heat_index" field.
func HeatIndexIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldHeatIndex, vs...))
}

// HeatIndexNotIn applies the NotIn predicate on the "heat_index" field.
func HeatIndexNotIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldHeatIndex, vs...))
}

// HeatIndexGT applies the GT predicate on the "heat_index" field.
func HeatIndexGT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldHeatIndex, v))
}

// HeatIndexGTE applies the GTE predicate on the "heat_index" field.
func HeatIndexGTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldHeatIndex, v))
}

// HeatIndexLT applies the LT predicate on the "heat_index" field.
func HeatIndexLT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldHeatIndex, v))
}

// HeatIndexLTE applies the LTE predicate on the "heat_index" field.
func HeatIndexLTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldHeatIndex, v))
}

// TemperatureProviderEQ applies the EQ predicate on the "temperature_provider" field.
func TemperatureProviderEQ(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldTemperatureProvider, v))
}

// TemperatureProviderNEQ applies the NEQ predicate on the "temperature_provider" field.
func TemperatureProviderNEQ(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldTemperatureProvider, v))
}

// TemperatureProviderIn applies the In predicate on the "temperature_provider" field.
func TemperatureProviderIn(vs ...string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldTemperatureProvider, vs...))
}

// TemperatureProviderNotIn applies the NotIn predicate on the "temperature_provider" field.
func TemperatureProviderNotIn(vs ...string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldTemperatureProvider, vs...))
}

// TemperatureProviderGT applies the GT predicate on the "temperature_provider" field.
func TemperatureProviderGT(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldTemperatureProvider, v))
}

// TemperatureProviderGTE applies the GTE predicate on the "temperature_provider" field.
func TemperatureProviderGTE(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldTemperatureProvider, v))
}

// TemperatureProviderLT applies the LT predicate on the "temperature_provider" field.
func TemperatureProviderLT(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldTemperatureProvider, v))
}

// TemperatureProviderLTE applies the LTE predicate on the "temperature_provider" field.
func TemperatureProviderLTE(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldTemperatureProvider, v))
}

// TemperatureProviderContains applies the Contains predicate on the "temperature_provider" field.
func TemperatureProviderContains(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldContains(FieldTemperatureProvider, v))
}

// TemperatureProviderHasPrefix applies the HasPrefix predicate on the "temperature_provider" field.
func TemperatureProviderHasPrefix(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldHasPrefix(FieldTemperatureProvider, v))
}

// TemperatureProviderHasSuffix applies the HasSuffix predicate on the "temperature_provider" field.
func TemperatureProviderHasSuffix(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldHasSuffix(FieldTemperatureProvider, v))
}

// TemperatureProviderEqualFold applies the EqualFold predicate on the "temperature_provider" field.
func TemperatureProviderEqualFold(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEqualFold(FieldTemperatureProvider, v))
}

// TemperatureProviderContainsFold applies the ContainsFold predicate on the "temperature_provider" field.
func TemperatureProviderContainsFold(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldContainsFold(FieldTemperatureProvider, v))
}

// LatEQ applies the EQ predicate on the "lat" field.
func LatEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldLat, v))
}

// LatNEQ applies the NEQ predicate on the "lat" field.
func LatNEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldLat, v))
}

// LatIn applies the In predicate on the "lat" field.
func LatIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldLat, vs...))
}

// LatNotIn applies the NotIn predicate on the "lat" field.
func LatNotIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldLat, vs...))
}

// LatGT applies the GT predicate on the "lat" field.
func LatGT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldLat, v))
}

// LatGTE applies the GTE predicate on the "lat" field.
func LatGTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldLat, v))
}

// LatLT applies the LT predicate on the "lat" field.
func LatLT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldLat, v))
}

// LatLTE applies the LTE predicate on the "lat" field.
func LatLTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldLat, v))
}

// LatIsNil applies the IsNil predicate on the "lat" field.
func LatIsNil() predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIsNull(FieldLat))
}

// LatNotNil applies the NotNil predicate on the "lat" field.
func LatNotNil() predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotNull(FieldLat))
}

// LonEQ applies the EQ predicate on the "lon" field.
func LonEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldLon, v))
}

// LonNEQ applies the NEQ predicate on the "lon" field.
func LonNEQ(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldLon, v))
}

// LonIn applies the In predicate on the "lon" field.
func LonIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldLon, vs...))
}

// LonNotIn applies the NotIn predicate on the "lon" field.
func LonNotIn(vs ...float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldLon, vs...))
}

// LonGT applies the GT predicate on the "lon" field.
func LonGT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldLon, v))
}

// LonGTE applies the GTE predicate on the "lon" field.
func LonGTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldLon, v))
}

// LonLT applies the LT predicate on the "lon" field.
func LonLT(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldLon, v))
}

// LonLTE applies the LTE predicate on the "lon" field.
func LonLTE(v float64) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldLon, v))
}

// LonIsNil applies the IsNil predicate on the "lon" field.
func LonIsNil() predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIsNull(FieldLon))
}

// LonNotNil applies the NotNil predicate on the "lon" field.
func LonNotNil() predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotNull(FieldLon))
}

// LocationProviderEQ applies the EQ predicate on the "location_provider" field.
func LocationProviderEQ(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldLocationProvider, v))
}

// LocationProviderNEQ applies the NEQ predicate on the "location_provider" field.
func LocationProviderNEQ(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldLocationProvider, v))
}

// LocationProviderIn applies the In predicate on the "location_provider" field.
func LocationProviderIn(vs ...string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldLocationProvider, vs...))
}

// LocationProviderNotIn applies the NotIn predicate on the "location_provider" field.
func LocationProviderNotIn(vs ...string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldLocationProvider, vs...))
}

// LocationProviderGT applies the GT predicate on the "location_provider" field.
func LocationProviderGT(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldLocationProvider, v))
}

// LocationProviderGTE applies the GTE predicate on the "location_provider" field.
func LocationProviderGTE(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldLocationProvider, v))
}

// LocationProviderLT applies the LT predicate on the "location_provider" field.
func LocationProviderLT(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldLocationProvider, v))
}

// LocationProviderLTE applies the LTE predicate on the "location_provider" field.
func LocationProviderLTE(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldLocationProvider, v))
}

// LocationProviderContains applies the Contains predicate on the "location_provider" field.
func LocationProviderContains(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldContains(FieldLocationProvider, v))
}

// LocationProviderHasPrefix applies the HasPrefix predicate on the "location_provider" field.
func LocationProviderHasPrefix(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldHasPrefix(FieldLocationProvider, v))
}

// LocationProviderHasSuffix applies the HasSuffix predicate on the "location_provider" field.
func LocationProviderHasSuffix(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldHasSuffix(FieldLocationProvider, v))
}

// LocationProviderIsNil applies the IsNil predicate on the "location_provider" field.
func LocationProviderIsNil() predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIsNull(FieldLocationProvider))
}

// LocationProviderNotNil applies the NotNil predicate on the "location_provider" field.
func LocationProviderNotNil() predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotNull(FieldLocationProvider))
}

// LocationProviderEqualFold applies the EqualFold predicate on the "location_provider" field.
func LocationProviderEqualFold(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEqualFold(FieldLocationProvider, v))
}

// LocationProviderContainsFold applies the ContainsFold predicate on the "location_provider" field.
func LocationProviderContainsFold(v string) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldContainsFold(FieldLocationProvider, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DeviceReading {
	return predicate.DeviceReading(sql.FieldLTE(FieldCreatedAt, v))
}

// HasDevice applies the HasEdge predicate on the "device" edge.
func HasDevice() predicate.DeviceReading {
	return predicate.DeviceReading(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceWith applies the HasEdge predicate on the "device" edge with a given conditions (other predicates).
func HasDeviceWith(preds ...predicate.Device) predicate.DeviceReading {
	return predicate.DeviceReading(func(s *sql.Selector) {
		step := newDeviceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeviceReading) predicate.DeviceReading {
	return predicate.DeviceReading(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeviceReading) predicate.DeviceReading {
	return predicate.DeviceReading(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeviceReading) predicate.DeviceReading {
	return predicate.DeviceReading(sql.NotPredicates(p))
}
