// Code generated by ent, DO NOT EDIT.

package pmsreading

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the pmsreading type in the database.
	Label = "pms_reading"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPm10 holds the string denoting the pm1_0 field in the database.
	FieldPm10 = "pm1_0"
	// FieldPm25 holds the string denoting the pm2_5 field in the database.
	FieldPm25 = "pm2_5"
	// FieldPm100 holds the string denoting the pm10_0 field in the database.
	FieldPm100 = "pm10_0"
	// FieldAqi holds the string denoting the aqi field in the database.
	FieldAqi = "aqi"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the pmsreading in the database.
	Table = "pms_readings"
)

// Columns holds all SQL columns for pmsreading fields.
var Columns = []string{
	FieldID,
	FieldPm10,
	FieldPm25,
	FieldPm100,
	FieldAqi,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// Pm10Validator is a validator for the "pm1_0" field. It is called by the builders before save.
	Pm10Validator func(float64) error
	// Pm25Validator is a validator for the "pm2_5" field. It is called by the builders before save.
	Pm25Validator func(float64) error
	// Pm100Validator is a validator for the "pm10_0" field. It is called by the builders before save.
	Pm100Validator func(float64) error
	// AqiValidator is a validator for the "aqi" field. It is called by the builders before save.
	AqiValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the PMSReading queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPm10 orders the results by the pm1_0 field.
func ByPm10(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPm10, opts...).ToFunc()
}

// ByPm25 orders the results by the pm2_5 field.
func ByPm25(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPm25, opts...).ToFunc()
}

// ByPm100 orders the results by the pm10_0 field.
func ByPm100(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPm100, opts...).ToFunc()
}

// ByAqi orders the results by the aqi field.
func ByAqi(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAqi, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
