// Code generated by ent, DO NOT EDIT.

package pmsreading

import (
	"go-aiq-backend/internal/platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldLTE(FieldID, id))
}

// Pm10 applies equality check predicate on the "pm1_0" field. It's identical to Pm10EQ.
func Pm10(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldEQ(FieldPm10, v))
}

// Pm25 applies equality check predicate on the "pm2_5" field. It's identical to Pm25EQ.
func Pm25(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldEQ(FieldPm25, v))
}

// Pm100 applies equality check predicate on the "pm10_0" field. It's identical to Pm100EQ.
func Pm100(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldEQ(FieldPm100, v))
}

// Aqi applies equality check predicate on the "aqi" field. It's identical to AqiEQ.
func Aqi(v int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldEQ(FieldAqi, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldEQ(FieldCreatedAt, v))
}

// Pm10EQ applies the EQ predicate on the "pm1_0" field.
func Pm10EQ(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldEQ(FieldPm10, v))
}

// Pm10NEQ applies the NEQ predicate on the "pm1_0" field.
func Pm10NEQ(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldNEQ(FieldPm10, v))
}

// Pm10In applies the In predicate on the "pm1_0" field.
func Pm10In(vs ...float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldIn(FieldPm10, vs...))
}

// Pm10NotIn applies the NotIn predicate on the "pm1_0" field.
func Pm10NotIn(vs ...float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldNotIn(FieldPm10, vs...))
}

// Pm10GT applies the GT predicate on the "pm1_0" field.
func Pm10GT(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldGT(FieldPm10, v))
}

// Pm10GTE applies the GTE predicate on the "pm1_0" field.
func Pm10GTE(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldGTE(FieldPm10, v))
}

// Pm10LT applies the LT predicate on the "pm1_0" field.
func Pm10LT(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldLT(FieldPm10, v))
}

// Pm10LTE applies the LTE predicate on the "pm1_0" field.
func Pm10LTE(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldLTE(FieldPm10, v))
}

// Pm25EQ applies the EQ predicate on the "pm2_5" field.
func Pm25EQ(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldEQ(FieldPm25, v))
}

// Pm25NEQ applies the NEQ predicate on the "pm2_5" field.
func Pm25NEQ(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldNEQ(FieldPm25, v))
}

// Pm25In applies the In predicate on the "pm2_5" field.
func Pm25In(vs ...float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldIn(FieldPm25, vs...))
}

// Pm25NotIn applies the NotIn predicate on the "pm2_5" field.
func Pm25NotIn(vs ...float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldNotIn(FieldPm25, vs...))
}

// Pm25GT applies the GT predicate on the "pm2_5" field.
func Pm25GT(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldGT(FieldPm25, v))
}

// Pm25GTE applies the GTE predicate on the "pm2_5" field.
func Pm25GTE(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldGTE(FieldPm25, v))
}

// Pm25LT applies the LT predicate on the "pm2_5" field.
func Pm25LT(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldLT(FieldPm25, v))
}

// Pm25LTE applies the LTE predicate on the "pm2_5" field.
func Pm25LTE(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldLTE(FieldPm25, v))
}

// Pm100EQ applies the EQ predicate on the "pm10_0" field.
func Pm100EQ(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldEQ(FieldPm100, v))
}

// Pm100NEQ applies the NEQ predicate on the "pm10_0" field.
func Pm100NEQ(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldNEQ(FieldPm100, v))
}

// Pm100In applies the In predicate on the "pm10_0" field.
func Pm100In(vs ...float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldIn(FieldPm100, vs...))
}

// Pm100NotIn applies the NotIn predicate on the "pm10_0" field.
func Pm100NotIn(vs ...float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldNotIn(FieldPm100, vs...))
}

// Pm100GT applies the GT predicate on the "pm10_0" field.
func Pm100GT(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldGT(FieldPm100, v))
}

// Pm100GTE applies the GTE predicate on the "pm10_0" field.
func Pm100GTE(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldGTE(FieldPm100, v))
}

// Pm100LT applies the LT predicate on the "pm10_0" field.
func Pm100LT(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldLT(FieldPm100, v))
}

// Pm100LTE applies the LTE predicate on the "pm10_0" field.
func Pm100LTE(v float64) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldLTE(FieldPm100, v))
}

// AqiEQ applies the EQ predicate on the "aqi" field.
func AqiEQ(v int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldEQ(FieldAqi, v))
}

// AqiNEQ applies the NEQ predicate on the "aqi" field.
func AqiNEQ(v int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldNEQ(FieldAqi, v))
}

// AqiIn applies the In predicate on the "aqi" field.
func AqiIn(vs ...int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldIn(FieldAqi, vs...))
}

// AqiNotIn applies the NotIn predicate on the "aqi" field.
func AqiNotIn(vs ...int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldNotIn(FieldAqi, vs...))
}

// AqiGT applies the GT predicate on the "aqi" field.
func AqiGT(v int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldGT(FieldAqi, v))
}

// AqiGTE applies the GTE predicate on the "aqi" field.
func AqiGTE(v int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldGTE(FieldAqi, v))
}

// AqiLT applies the LT predicate on the "aqi" field.
func AqiLT(v int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldLT(FieldAqi, v))
}

// AqiLTE applies the LTE predicate on the "aqi" field.
func AqiLTE(v int) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldLTE(FieldAqi, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PMSReading {
	return predicate.PMSReading(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PMSReading) predicate.PMSReading {
	return predicate.PMSReading(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PMSReading) predicate.PMSReading {
	return predicate.PMSReading(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PMSReading) predicate.PMSReading {
	return predicate.PMSReading(sql.NotPredicates(p))
}
