-- Create "device_readings" table
CREATE TABLE "public"."device_readings" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "pm1_0" double precision NOT NULL,
  "pm2_5" double precision NOT NULL,
  "pm10_0" double precision NOT NULL,
  "pms_provider" character varying NOT NULL,
  "aqi" bigint NOT NULL,
  "temperature" double precision NOT NULL,
  "humidity" double precision NOT NULL,
  "heat_index" double precision NOT NULL,
  "temperature_provider" character varying NOT NULL,
  "lat" double precision NULL,
  "lon" double precision NULL,
  "location_provider" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "device_id" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "device_readings_devices_readings" FOREIGN KEY ("device_id") REFERENCES "public"."devices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "devicereading_created_at" to table: "device_readings"
CREATE INDEX "devicereading_created_at" ON "public"."device_readings" ("created_at");
-- Create index "devicereading_device_id_created_at" to table: "device_readings"
CREATE INDEX "devicereading_device_id_created_at" ON "public"."device_readings" ("device_id", "created_at");
-- Drop "pms_readings" table
DROP TABLE "public"."pms_readings";
