-- create "devices" table
CREATE TABLE "devices" ("id" uuid NOT NULL, "device_id" character varying NOT NULL, "name" character varying NOT NULL, "device_key" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "device_created_at" to table: "devices"
CREATE INDEX "device_created_at" ON "devices" ("created_at");
-- create index "devices_device_id_key" to table: "devices"
CREATE UNIQUE INDEX "devices_device_id_key" ON "devices" ("device_id");
-- create "pms_readings" table
CREATE TABLE "pms_readings" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "pm1_0" double precision NOT NULL, "pm2_5" double precision NOT NULL, "pm10_0" double precision NOT NULL, "aqi" bigint NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- create index "pmsreading_created_at" to table: "pms_readings"
CREATE INDEX "pmsreading_created_at" ON "pms_readings" ("created_at");
