-- Create "devices" table
CREATE TABLE "public"."devices" (
  "id" uuid NOT NULL,
  "device_id" character varying NOT NULL,
  "name" character varying NOT NULL,
  "owner_id" character varying NULL,
  "is_outdoor" boolean NOT NULL DEFAULT false,
  "is_public" boolean NOT NULL DEFAULT false,
  "device_key" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "device_created_at" to table: "devices"
CREATE INDEX "device_created_at" ON "public"."devices" ("created_at");
-- Create index "device_owner_id_created_at" to table: "devices"
CREATE INDEX "device_owner_id_created_at" ON "public"."devices" ("owner_id", "created_at");
-- Create index "devices_device_id_key" to table: "devices"
CREATE UNIQUE INDEX "devices_device_id_key" ON "public"."devices" ("device_id");
-- Create "device_readings" table
CREATE TABLE "public"."device_readings" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "pm1_0" double precision NOT NULL,
  "pm2_5" double precision NOT NULL,
  "pm10_0" double precision NOT NULL,
  "pms_provider" character varying NOT NULL,
  "aqi" bigint NOT NULL,
  "temperature" double precision NOT NULL,
  "humidity" double precision NOT NULL,
  "heat_index" double precision NOT NULL,
  "temperature_provider" character varying NOT NULL,
  "lat" double precision NULL,
  "lon" double precision NULL,
  "location_provider" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "device_id" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "device_readings_devices_readings" FOREIGN KEY ("device_id") REFERENCES "public"."devices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "devicereading_created_at" to table: "device_readings"
CREATE INDEX "devicereading_created_at" ON "public"."device_readings" ("created_at");
-- Create index "devicereading_device_id_created_at" to table: "device_readings"
CREATE INDEX "devicereading_device_id_created_at" ON "public"."device_readings" ("device_id", "created_at");
