// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DevicesColumns holds the columns for the "devices" table.
	DevicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "device_id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "device_key", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DevicesTable holds the schema information for the "devices" table.
	DevicesTable = &schema.Table{
		Name:       "devices",
		Columns:    DevicesColumns,
		PrimaryKey: []*schema.Column{DevicesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "device_created_at",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[4]},
			},
		},
	}
	// PmsReadingsColumns holds the columns for the "pms_readings" table.
	PmsReadingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "pm1_0", Type: field.TypeFloat64},
		{Name: "pm2_5", Type: field.TypeFloat64},
		{Name: "pm10_0", Type: field.TypeFloat64},
		{Name: "aqi", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PmsReadingsTable holds the schema information for the "pms_readings" table.
	PmsReadingsTable = &schema.Table{
		Name:       "pms_readings",
		Columns:    PmsReadingsColumns,
		PrimaryKey: []*schema.Column{PmsReadingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "pmsreading_created_at",
				Unique:  false,
				Columns: []*schema.Column{PmsReadingsColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DevicesTable,
		PmsReadingsTable,
	}
)

func init() {
}
